### ISSUE TITLE
Unable to use Admin group name containing special characters

### ISSUE THREAD

**Issue by warnes** [openanalytics/shinyproxy#108]
For reasons I won’t go into here, I am getting group names via OpenId in LDAP syntax, for instance:
“CN=BI Sales Super User,OU=Company Groups,DC=Company,DC=ICD”

I can successfully use this group name for access to apps:
```
...
  specs:
  - id: sales_app
    container-cmd: ["R", "-e", "shinyproxy::run_sales_app()"]
    container-image: sales_app
    access-groups: [ "CN=BI Sales Super User,OU=Company Groups,DC=Company,DC=ICD"  ]
...
```
However, using this name for admin-groups does not work:
```
proxy:
  ...
  admin-groups: "CN=COE,OU=OKTA GROUPS,OU=ATD GROUPS,DC=ATD-US,DC=ICD"
  ...
```

Any ideas?
