### ISSUE TITLE
Is it possible to set the username (not email) from auth0 as SHINYPROXY_USERNAME?

### ISSUE THREAD

**Issue by shizidushu** [openanalytics/shinyproxy#109]
Just test shinyproxy with auth0.

I want to set the username (not email) as SHINYPROXY_USERNAME. I try to do it by set proxy.openid.username-attribute: nickname. Then the broswwer complains

The page isn’t redirecting properly. An error occurred during a connection to ****.auth0.com. This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by fmichielssen** [comment]
Hi @shizidushu ,

The `nickname` attribute is included in the `profile` scope (more info [here](https://auth0.com/docs/scopes/current/oidc-scopes)), but ShinyProxy does not request that scope by default. To get it, use the following configuration:

    proxy:
      openid:
        username-attribute: nickname
        scopes: [ "profile" ]

**Comment by shizidushu** [comment]
Thank you very much. It is working.

**Comment by gacolitti** [comment]
What about using the username?

This doesn't seem to do it for me:
```
proxy:
  openid:
    username-attribute: username
    scopes: [ "profile" ]
```

But I can view the user on Auth0 and see that there is a username.

**Comment by dselivanov** [comment]
Just to make it clear for newcomers (and less familiar with java magic as myself). You can expose it AUTH0 user id as env var during container start and use it in runtime. 

Add something like following to your `applications.yml`:

```yaml
proxy:
  authentication: openid
  # ...
  # params
  specs:
  - id: app_id
    # ...
    # app params
    container-env:
      AUTH0_USER_ID: "#{oidcUser.attributes['sub']}"

```
