### ISSUE TITLE
[FEATURE REQUEST] choose between app or app_direct in landing page

### ISSUE THREAD

**Issue by dylancis** [openanalytics/shinyproxy#144]
it seems there is no way we can specify the redirect mode `/app/` vs `/app_direct/` via the ShinyProxy landing page (INDEX index page).

![image](https://user-images.githubusercontent.com/4976433/56297663-a5d07900-6128-11e9-906f-1044a8d774d6.png)

It would be useful to have an option within the configuration YAML file such as:

```
 specs:
  - id: 01_hello
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
    app_url: app_direct (or app)
```

**Comment by dylancis** [comment]
@tverbeke  I believe the line in question is here:
https://github.com/openanalytics/shinyproxy/blob/7c5448223fcff55f29ad630f7ac36d380ff68597/src/main/java/eu/openanalytics/shinyproxy/controllers/AppController.java#L112

**Comment by dylancis** [comment]
@tobias-verbeke  maybe here:
https://github.com/openanalytics/shinyproxy/blob/7c5448223fcff55f29ad630f7ac36d380ff68597/src/main/resources/templates/index.html#L42

**Comment by gazetapl** [comment]
It's not the prettiest solution, but I've changed two following lines in 2col template  

> Line 43 in [index.html](https://github.com/openanalytics/shinyproxy-config-examples/blob/master/04-custom-html-template/templates/2col/index.html)  `<a th:href="${#strings.contains(app.id, '_fs')} ? @{/app_direct/}+${app.id}+@{/} : @{/app/}+${app.id}">`
>Line 49 in [index.html](https://github.com/openanalytics/shinyproxy-config-examples/blob/master/04-custom-html-template/templates/2col/index.html)  `<a th:href="${#strings.contains(app.id, '_fs')} ? @{/app_direct/}+${app.id}+@{/} : @{/app/}+${app.id}" th:text="${app.displayName == null} ? ${app.id} : ${app.displayName}"></a>	`	
 
Now if you want some app to be displayed without navbar, in you YAML file add `'_fs'` in id i.e.

```
specs:
  - id: 01_hello_fs
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
```
