### ISSUE TITLE
Error  Status code: 500  Message: Failed to start container 

### ISSUE THREAD

**Issue by kochkina** [openanalytics/shinyproxy#173]
Hello. I have a problem when I'm trying to start ShinyProxy with Dash.
I tried this docker image https://github.com/openanalytics/shinyproxy-dash-demo. Unfortunately there aren't any examples of application.yml file with this container image. I'm novice and it's my first attempt to create dash report in conjuction with Shinyproxy. Could you help me please to figure out where I'm making a mistake

> Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8050 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

application.yml:
```
proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
    url: http://localhost:8050
  specs:
  - id: dash-demo
    display-name: Dash Demo Application
    description: Simple random scatterplot
    container-cmd:  ["python", "/app/app.py"]
    container-image: shinyproxy-dash-demo

logging:
  file:
    shinyproxy.log
```

**Comment by tverbeke** [comment]
Hi @kochkina,

Thank you for your question and interest in ShinyProxy.

The `docker` settings are related to communicating with the Docker daemon (the 8050 looks bizarre there)  and have nothing to do with the Dash app port which is specified inside the spec for the app as in

```
  specs:
  - id: dash-demo
    display-name: Dash Demo Application
    description: Simple random scatterplot
    port: 8050
    container-cmd:  ["python", "/app/app.py"]
    container-image: shinyproxy-dash-demo
```

HTH,
Tobias
