### ISSUE TITLE
Shinyproxy to launch jupyter notebook with docker?

### ISSUE THREAD

**Issue by thomas-chauvet** [openanalytics/shinyproxy#174]
Hello,

As you did for [zeppelin notebook](https://github.com/openanalytics/shinyproxy-zeppelin-notebook-demo), is there a way to serve jupyter notebook with Shinyproxy ?

I tried with:
```yml
specs:
    id: jupyter-notebook
    display-name: jupyter-notebook
    description: Jupyter Notebook is a web-based interactive computational environment for creating Jupyter notebook documents.
    container-cmd: ["jupyter", "notebook","--NotebookApp.token=''","--NotebookApp.password=''", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
    container-image: jupyter/datascience-notebook
    container-network: shinyproxy-network
    port: 8888
```
Bit without success. I just have a `404`..

Thanks for your help :)
