### ISSUE TITLE
Kubernetes - pod resource request and limits are not being set

### ISSUE THREAD

**Issue by dgrapov** [openanalytics/shinyproxy#183]
Hi,

Thank you for your excellent product. I am running  `shinyproxy-2.3.0` on AWS EKS with `kubectl v1.16.2` and `server version 1.13.12-eks-c500e1`. 

I am unable to configure shinyproxy to set pod `cpu` and `memory` resource request and limits. Based on the description at https://www.shinyproxy.io/configuration/#kubernetes the following should set all pod request and limits.

```
container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    image-pull-policy: Always
    container-memory-request: "500Mi"
    container-memory-limit: "700Mi"
    container-cpu-request: "700m"
    container-cpu-limit: "900m"
```

My expectation is that the request above should be set for the pod. However these are absent when viewing the pod via `kubecl describe` e.g. the following block is absent.

```
Containers:
    Limits:
      cpu:     700m
      memory:  700Mi
    Requests:
      cpu:       900m
      memory:    500Mi
```

The request is also absent when executing `kubectl describe nodes` e.g. absent for the `sp-pod-XXXX` below.

```
  Namespace                  Name                                           CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                           ------------  ----------  ---------------  -------------  ---
shinyproxy-app             shinyproxy-6dfccf858f-ttrzv                    350m (35%)    625m (62%)  350Mi (18%)      650Mi (34%)    12m
shinyproxy-app             sp-pod-b642d05f-5563-4213-abda-eb040e7e7e76    0 (0%)        0 (0%)      0 (0%)           0 (0%)         11m

```

The shinyproxy logs do not show any related warnings and no errors. The pods launch fine but the server does not budget their resource requests when assigning to a node. This breaks cluster autoscaling and leaves nodes unresponsive when pods require more cpu or memory than the node has available.

I can confirm that cluster autoscaling and horizontal pod scaling both work as expected when pods are launched via `kubectl` with explicit resource requests and limits.

Please let me know if I can provide any additional `debug` info. I look forward to hearing your suggestions regarding this issue.

**Comment by tverbeke** [comment]
Hi @dgrapov This is indeed probably a bug. We will investigate.

**Comment by kuzmenkov111** [comment]
I have the same issue but on docker host. 
I can’t figure out how to set container-memory-limit value. I have tried, but ShinyProxy runs containers without memory usage limitations. Docker host configuration is OK - it runs containers with memory limits.

Here is my application.yml file. What is wrong?

```
spring:
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
proxy:
  title: APP
  template-path: ./templates/1col
  favicon-path: favicon.png
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /app_direct/my_app
  port: 8080
  heartbeat-timeout: 60000
  authentication: webservice
  webservice:
    authentication-url: https://127.0.0.1:8081/api/auth/check
    authentication-request-body: "{email: '%s', password: '%s'}" 
  hide-navbar: true
  admin-groups: admins
  container-backend: docker
  docker:
    internal-networking: true
    container-memory-limit: "1G"
    container-memory-request: "300M"
    #container-cpu-limit: 0.3, 5
  #container-log-path: ./log
  specs:
  - id: Myapp
    display-name: Test_NAME
    description: Test
    container-cmd: ["R", "-e shiny::runApp('/home/dockerapp/app',port=3838,host='0.0.0.0')"]
    container-image: myimage

```
