### ISSUE TITLE
Connect to multiple networks

### ISSUE THREAD

**Issue by billy34** [openanalytics/shinyproxy#185]
Hello
I'm using a dockerized shinyproxy with a docker backend
Everything works fine but I didn't find a way to connect an app to more that one network

```
container-backend: docker
docker:
  container-protocol: http
  internal-networking: true
spec:
  - id: myapp
    display-name: my app
    container-image: me/myapp
    container-network: shinyproxy_backend
```

I would like to connect myapp also on another network to access a database.

I tried `container-network: [ shinyproxy_backend, db_network ]` and 
```
container-network:
  - shinyproxy_backend
  - db_network
```
with no luck

Is it possible ?
