### ISSUE TITLE
Pass sensitive environment variables to container

### ISSUE THREAD

**Issue by antoine-sachet** [openanalytics/shinyproxy#187]
My shinyproxy server has environment variables (let's say `DB_USER` and `DB_PWD`) that I need to pass on to one of my apps. Is this possible?

Basically do something like:

```
proxy:
  specs:
    - id: demo-app
      container-image: ...
      container-env:
        DB_USER: $DB_USER
        DB_PWD: $DB_PWD
```

I don't want to hardcode credentials in `application.yml` since it is under version control. 

For context, I run a dockerized shinyproxy server on AWS EC2. With Amazon, credentials are typically passed from the AWS parameter store as environment variables at runtime. I need to transfer the environment variables.

```
AWS parameter store  >> Shinyproxy server (Host) >> App (Container)
DB_USER=...                    DB_USER=...                     ?
DB_PWD=...                     DB_PWD=...                      ?
```

Is this possible? If yes, it should be documented in https://www.shinyproxy.io/configuration/
