### ISSUE TITLE
docker-compose.yml configuration

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#203]
Hi,

I would like to know, please, what's the difference between using `restart: always` and `restart: on-failure` in the docker-compose.yml file (shinyproxy service).

```
version: "3.6"
services:
  shinyproxy:
    image: datanovia/shinyproxy
    container_name: dnv_shinyproxy
    restart: always
    build: ./shinyproxy
    networks:
      - dnv-net
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/server:/log"
      - "./shinyproxy-logs/container:/container-logs"
      - "./shinyproxy/application.yml:/opt/shinyproxy/application.yml"
      - "./shinyproxy/templates:/opt/shinyproxy/templates"
  app:
    image: app-docker
    container_name: dnv_app
    build: ./shinyapps/app-docker
    networks:
      - dnv-net

networks:
  dnv-net:
    name: dnv-net
```
Thank you so much.
