### ISSUE TITLE
Direct Path to local drive in Application.yml

### ISSUE THREAD

**Issue by deepanshu88** [openanalytics/shinyproxy#206]
Is there any way we can give path of app which is in local drive in container-cmd and container-volumes in application.yml? I am aware of the method to copy files using COPY command in image and then use that path in container-cmd? I was wondering if container-volumes would speed up opening and processing container.

```
testing
├── Dockerfile
├── Rprofile.site
└── shinyapps
      ├── server.R
      └── ui.R
└── shinyproxy
    ├── Dockerfile
    └── application.yml
```
Application.yml

```
proxy:
  title: Analytics Dashboards
  template-path: ./templates/2col
  hide-navbar: true
  port: 8080


  docker:
      internal-networking: true
  specs:
  - id: country
    display-name: Country Dashboard
    description: Dashboard showing country level performance
    container-cmd: ["R", "-e", "shiny::runApp('/shinyapps/countrydashboard', host = '0.0.0.0', port = 3838)"]
    container-image: country
    container-network: sp-example-net
    container-volumes: ["C:/Users/dsa/testing/shinyapps:/countrydashboard"]



logging:
  file:
    shinyproxy.log
```
