### ISSUE TITLE
Sys.getenv("SHINYPROXY_USERGROUPS")) returns empty string

### ISSUE THREAD

**Issue by panoptikum** [openanalytics/shinyproxy#219]
Hello,

I was trying to condition some part of my app on certain user groups, however if try to retrieve the user groups of the logged in user I only get an empty object:

`Sys.getenv("SHINYPROXY_USERGROUPS"))`

If I try to access the user via:

`print(Sys.getenv("SHINYPROXY_USERNAME"))
`
it works perfectly.

To give a reproducible example, my application.yml looks as follows:

```
proxy:
  port: 8081
  authentication: simple
  admin-groups: admins
  container-log-path: home/felix/container-logs
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
    groups: pv_qs
  - name: jane
    password: password
    groups: [management, test]
  docker:
      internal-networking: true
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 02_lifecycle
    display-name: Lifecycle
    container-cmd:  ["R", "-e", "shiny::runApp('/root/lifecycle')"]
    container-image: lifecycle
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log
```
Is this a known bug? Any hints for a solution?

Much appreciated.
