### ISSUE TITLE
ShinyProxy not serving on 8080 port.

### ISSUE THREAD

**Issue by sarthi2395** [openanalytics/shinyproxy#226]
I am trying to install ShinyProxy in a local server The **application.yaml** config I use

````
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: http://www.openanalytics.eu/sites/www.openanalytics.eu/themes/oa/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: ldap
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: scientists

logging:
  file:
    shinyproxy.log
````

ShinyProxy is running as a service on port 8080. 

````
● shinyproxy.service - ShinyProxy
   Loaded: loaded (/etc/systemd/system/shinyproxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2020-08-27 08:43:30 IST; 5 days ago
 Main PID: 31430 (java)
    Tasks: 40
   Memory: 897.8M
   CGroup: /system.slice/shinyproxy.service
           └─31430 /usr/bin/java -jar /opt/shinyproxy/shinyproxy.jar
````

However, if I curl the URL, it says 
````
$ curl localhost:8080
curl: (7) Failed connect to localhost:8080; Connection refused

````

My docker is up and running on 2375 and I can spin up a test container and access it over browser. So that doesn't seem to be the problem here. Could anyone help me out?
