### ISSUE TITLE
OWASP/Security Checks

### ISSUE THREAD

**Issue by benkates** [openanalytics/shinyproxy#229]
Hi there, an enterprise client is asking about an OWASP check for ShinyProxy - is there any detail you can give on checks you do or vulnerabilities that have been found and addressed?

**Comment by tverbeke** [comment]
Hi @benkates Some customers went through pentesting and formal audits of their ShinyProxy infrastructure. We have worked with them to include minor changes to make the software OWASP proof. In the release notes of version 2.3.1 you will notice a lot of small security enhancements that originate in this exercise: https://shinyproxy.io/downloads/

Hope this helps!

Best,
Tobias

**Comment by benkates** [comment]
Thanks, we implemented the following and got no major risks from the pen test results:

```
server:
  frameOptions: SAMEORIGIN
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
```
