### ISSUE TITLE
Injecting Vault Secrets Into Kubernetes Pods via a Sidecar

### ISSUE THREAD

**Issue by agarwva2** [openanalytics/shinyproxy#238]
Currently we are able to run our pod on kubernetes which fetches a secret to connect to database from kubernetes secrets in dev environment, using the below snippet in the application.yaml file

  - id: XYZ
    container-image: XYZ:latest
    container-env:
      TOKEN: "secretKeyRef:Secret:key"  

However we would like to avoid using kubernetes secret in production and look at ways to Injecting Vault Secrets Into Kubernetes Pods via a Sidecar - https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar

**Comment by agarwva2** [comment]
With the release of shinyproxy 2.4 and full k8s support, we were able to utilize the new pod patch feature to annotate the pod to inject the secret from vault using an init pod in the pod
 ```
kubernetes-pod-patches: |
      - op: add
        path: /spec/serviceAccountName
        value: <placeholder_of_serviceAccountName>
      - op: add
        path: /metadata/annotations
        value:
          vault.hashicorp.com/agent-inject: true
          vault.hashicorp.com/role: <placeholder_role_name>
          vault.hashicorp.com/agent-inject-secret-secret.sh: <"placeholder_Path_to_secret_secret/projects/<XYZ>/<ENV>/secrets">
          vault.hashicorp.com/auth-path: <"placeholder_auth-path">
          vault.hashicorp.com/agent-pre-populate-only: true
          vault.hashicorp.com/agent-inject-template-secret.sh: "{{ with secret \"secret/projects/<XYZ>/<ENV>/secrets\" -}} {{ range $k,$v := .Data.data }} export {{ $k }}=\"{{ $v }}\" {{ end }} {{- end }}"
          vault.hashicorp.com/tls-skip-verify: true
```
Debugging pod patches was tricky but luckily we have the below debug option, which really helped:-
```
proxy:
  kubernetes:
    debug-patches: true
```
