### ISSUE TITLE
SAML error: SAML message intended destination endpoint did not match the recipient endpoint

### ISSUE THREAD

**Issue by jat255** [openanalytics/shinyproxy#265]
I am fairly naive about SAML and the spring framework in general, but I am trying to configure our ShinyProxy server to use my organization's SAML server, and I'm receiving the following error after what appears to be a successful authentication:

`2021-01-21 19:22:52.748 ERROR 1 --- [  XNIO-1 task-1] o.o.c.b.decoding.BaseSAMLMessageDecoder  : SAML message intended destination endpoint 'https://myapphost/saml/SSO' did not match the recipient endpoint 'http://myapphost/scheduler/saml/SSO'`

The issue appears to be with something related to the `https`/`http` protocol being mismatched. This app is behind an Apache reverse proxy, which from what I've read might be causing the issue. The RP redirects from https://myhostname/myapp to the exposed Docker host port 8888 (as defined in my `application.yml` file). 

The apache config for this remote proxy is:

```conf
# Websocket stuff
# Needs the rewrite and proxy_wstunnel modules.
        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /scheduler/(.*)    ws://127.0.0.1:8888/myapp/$1 [P,L]

#
# Docker stuff for the scheduler.  Requires the proxy_http
# module to be enabled.
        ProxyPass /myapp http://127.0.0.1:8888/myapp
        ProxyPassReverse /myapp http://127.0.0.1:8888/myapp
```

Some related pages I've found in my search:
- https://github.com/openanalytics/containerproxy/pull/32
- https://docs.spring.io/spring-security-saml/docs/2.0.x/reference/html/configuration-advanced.html#configuration-load-balancing
- https://github.com/johannestang/shinyproxy-lb
- https://github.com/openanalytics/shinyproxy/issues/247

Here is my application.yml (with some private information changed/removed):

```yaml
proxy:
  authentication: saml
  title: My app
  favicon: file:///opt/shinyproxy/templates/favicon.ico
  admin-groups: admins
  logo-url: file:///opt/shinyproxy/templates/my_logo.png
  template-path: /opt/shinyproxy/templates/mytemplate
  bind-address: 0.0.0.0
  port: 8888
  # change the landing-page to restrict shinyproxy to one application:
  landing-page: /myapp/app/myapp
  saml:
    idp-metadata-url: <URL TO metadata XML>
    app-entity-id: <MY APP's DEPLOYMENT PATH>
    app-base-url: <MY APP's DEPLOYMENT PATH>
    name-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn
    roles-attribute: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
  support:
    mail-to-address: myemailaddress@me.com
  docker:
    internal-networking: true
    container-network: shinyproxy-net
  container-log-path: ./container-logs
  specs:
    - id: myapp
      display-name: My tool
      description: Description for my app
      container-cmd: ["R", "-e", "shiny::runApp('/root')"]
      container-image: my-image
      container-network: "${proxy.docker.container-network}"

# for email
spring:
  mail:
    host: my.smtp.server
    # TLS: 587 SSL: 465 Plain: 25
    port: 25

server:
  useForwardHeaders: true
  forward-headers-strategy: native
  servlet.session.timeout: 3600
  servlet:
    context-path: /myapp

logging:
  file:
    shinyproxy.log
```

I have tried this with ShinyProxy 2.4.3 deployed in Docker using the following Dockerfile:

```Dockerfile
FROM openjdk:8-jre

RUN mkdir -p /opt/shinyproxy/
RUN wget https://www.shinyproxy.io/downloads/shinyproxy-2.4.3.jar -O /opt/shinyproxy/shinyproxy.jar
COPY application.yml /opt/shinyproxy/application.yml
COPY templates/ /opt/shinyproxy/templates/


WORKDIR /opt/shinyproxy/
CMD ["java", "-jar", "/opt/shinyproxy/shinyproxy.jar"]
```

Any ideas if I can fix this issue by changing a configuration setting somewhere?
