### ISSUE TITLE
Authentication error with IdentityServer4

### ISSUE THREAD

**Issue by erossini** [openanalytics/shinyproxy#268]
HI,
I'm trying to connect the ShinyProxy with my IdentityServer4. The `application.yml` is the following one:

```
proxy:
  title: Open Analytics Shiny Proxy
  port: 8080

  authentication: openid
  openid:
    auth-url: https://myidsrv/connect/authorize
    token-url: https://myidsrv/connect/token
    jwks-url: https://myidsrv/.well-known/openid-configuration/jwks
    client-id: ShinyProxy
    client-secret: password
    scopes: ["openid", "profile"]
    username-attribute: name

  docker:
      internal-networking: true

  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net

logging:
  file:
    opt/shinyproxy/shinyproxy.log

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
```

When I open the ShinyProxy page, I redirect to the login page of the IdentityServer. Good. I login and the IdentityServer redirects me to 

> http(s)://(your-shinyproxy-url)/login/oauth2/code/shinyproxy

as in the [documentation](https://www.shinyproxy.io/configuration/#register-with-an-oidc-provider). Unfortunately, ShinyProxy has an error.

This is the result in Firefox on the Linux machine:

![image](https://user-images.githubusercontent.com/9497415/106130224-00e62b00-6159-11eb-8300-59ea5ec6e530.png)

This is the result in my Microsoft Edge browser:

![image](https://user-images.githubusercontent.com/9497415/106130353-25420780-6159-11eb-9f6d-d8cfac8e85ee.png)

I try to refresh the page a lot of times and then on the Linux machine I can see that:

![screenshot](https://user-images.githubusercontent.com/9497415/106131356-7bfc1100-615a-11eb-80dd-bd4adacbe469.png)

Then, I check the log but the log isn't created. 

### Basic
![image](https://user-images.githubusercontent.com/9497415/106257001-ecb33400-6213-11eb-8db8-e8c452771d5c.png)

### Authentication/Logout
![image](https://user-images.githubusercontent.com/9497415/106257073-ff2d6d80-6213-11eb-8a8f-77389cedc0f3.png)

### Token 
![image](https://user-images.githubusercontent.com/9497415/106257115-09e80280-6214-11eb-9f22-d427339167e4.png)

**Comment by LEDfan** [comment]
Hi

I don't have experience with IdentityServer4 and I don't see anything strange in your configuration.

Your ShinyProxy configuration for logging to a file seems to be wrong, please change it to the following, restart ShinyProxy and try again.

```
logging:
  file:
    name: /opt/shinyproxy/shinyproxy.log
````

Now a useful error should be logged and this should help you to debug the issue.
Good luck!

**Comment by LEDfan** [comment]
Hi @erossini

Since you opened a new issue regarding IdentityServer, is this issue solved? If so, could you explain how you managed to fix it? This could be interesting for the whole community.

**Comment by erossini** [comment]
Finally, I fixed the issue with the IdentityServer (oidc). The configuration in the screenshot about are correct. The problem was in the configuration file `application.yml`.

```
  authentication: openid
  openid:
    auth-url: https://identityserverurl/connect/authorize
    token-url: https://identityserverurl/connect/token
    jwks-url: https://identityserverurl/.well-known/openid-configuration/jwks
    logout-url: https://identityserverurl/Account/Logout?return=http://yoururl/
    client-id: #{IdSrvClientId}#
    client-secret: #{IdSrvClientSecret}#
    scopes: [ "openid", "profile", "roles" ]
    username-attribute: aud
```

What I have to implement now is the `roles` for the users. When I found a solution, I will post it and create a full explanation on my [blog](https://www.puresourcecode.com/).
