### ISSUE TITLE
Need to press sign in twice after logout

### ISSUE THREAD

**Issue by daniel1608** [openanalytics/shinyproxy#286]
We use ShinyProxy 2.5.0 on Kubernetes. As authentication method we use LDAP.
Our problem is that we need to press the button "Sign in" twice after a logout.
Steps:
1) Sign in -> works
2) Sign out -> works
3) Sign in -> page reloads
4) Sign in -> works

If we deploy ShinyProxy on a regular VM the problem does not occur. I'm not sure if the cause is on your side or on ours (some configuration not related to ShinyProxy). I would paste additional info from the logs but the default settings aren't verbose enough and I don't know for what module should change it.

Some settings from the application.yml
```
proxy:
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 240000
  authentication: ldap
  ldap:
    url: ldap://url/DC=hc,DC=lan
    # deleted the ldap config
  container-backend: kubernetes
  kubernetes:
    url: http://127.0.0.1:8001
    namespace: # deleted
    internal-networking: true
    pod-wait-time: 100000
```

Small gif of the problem. https://media.giphy.com/media/e7mUcy421PgZWXLJuE/giphy.gif

Does anyone have the same issues or can tell me what I could look for?
