### ISSUE TITLE
Accessing ID of proxy from inside container?

### ISSUE THREAD

**Issue by jat255** [openanalytics/shinyproxy#288]
As a workaround for #149, we have implemented some tooling within our app for users to report an issue. I would like to be able to attach the value of the proxy ID assigned by ShinyProxy to this message so our admins know which log file to look at (we're storing these using the `container-log-path` option). From inside the container, I can get the docker container ID (via `hostname`), but the logfile names are based off the UUID generated proxy ID. I see that's exposed in the labels of the docker container, but there's not a great way to access these within the container without bind-mounting `/var/run/docker.sock` into the container, which would have to be done internally by ShinyProxy:

```
            "Labels": {
                "openanalytics.eu/sp-instance": "ec8df65fd9f33c452147b7d510d936b1cd8d6e61",
                "openanalytics.eu/sp-proxied-app": "true",
                "openanalytics.eu/sp-proxy-created-timestamp": "1617227623391",
-->             "openanalytics.eu/sp-proxy-id": "df25f41c-8eda-4842-a8c3-39fac02550c0",
                "openanalytics.eu/sp-spec-id": "xxx",
                "openanalytics.eu/sp-user-groups": "xxx",
                "openanalytics.eu/sp-user-id": "xxx",
                "org.label-schema.license": "GPL-2.0",
            }
```

Is there any potential way I am missing that I could get access to this information?

As a future improvement, exposing all the shinyproxy docker labels as environment variables could be a nice way to provide that information to the container (like how `sp-user-id` maps to `SHINYPROXY_USERNAME`, etc.)

Thank you!

**Comment by LEDfan** [comment]
Hi

Thanks for opening this issue. You can provide the proxy-id as an environment variable using the following application configuration:

```yaml
specs:
  - id: rstudio
    container-image: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
    container-env:
      SHINYPROXY_PROXY_ID: "#{proxy.id}"
```

Regarding exposing all labels as env variable: I think this is a good idea, I think the main idea of not doing this was that it should be easy to add these variables yourself. On the other hand, there is not really a reason no to do it. In addition it makes using ShinyProxy a little bit easier, which we of course like.

For reference you can use the following configuration to expose all labels as env variables:

```
  specs:
  - id: rstudio
    container-image: openanalytics/shinyproxy-rstudio-ide-demo:1.4.1106__4.0.4
    container-env:
      SHINYPROXY_PROXY_ID: "#{proxy.id}"
      SHINYPROXY_CREATED_TIMESTAMP: "#{proxy.createdTimestamp}"
      SHINYPROXY_SPEC_ID: "#{proxySpec.id}"
      SHINYPROXY_INSTANCE: "#{proxySpec.containerSpecs[0].runtimeLabels.get('openanalytics.eu/sp-instance').second}" # I agree this is not a trivial one to setup...
```
