### ISSUE TITLE
[question] Mount k8s projected volumes

### ISSUE THREAD

**Issue by cristianburca** [openanalytics/shinyproxy#290]
Hi guys,

I'm looking for a possibility to mount some **projected** cert secret **volumes** as below since my shiny app requires a ssl connection. Can you please let me know if there is a way using **kubernetes-pod-patches**?
Thank you.

```
	volumeMounts:
	- mountPath: /app_folder/inst/app/cert/
	  name: ssl-store-files
	  readOnly: true
  volumes:
  - name: ssl-store-files
	projected:
	  defaultMode: 420
	  sources:
	  - secret:
		  items:
		  - key: ca.crt
			mode: 384
			path: ca.crt
		  name: sslrootcert-secret
	  - secret:
		  items:
		  - key: user.key
			mode: 384
			path: user.key
		  name: sslkey-user-secret
	  - secret:
		  items:
		  - key: user.crt
			mode: 384
			path: user.crt
		  name: sslcert-user-secret
```

**Comment by cristianburca** [comment]
Nevermind.

```
    kubernetes-pod-patches: |
      - op: add
        path: /spec/containers/0/volumeMounts
        value:
          - mountPath: "/app_folder/inst/app/cert/"
            name: "ssl-store-files"
            readOnly: true
      - op: add
        path: /spec/volumes
        value:
          - name: "ssl-store-files"
            projected:
              defaultMode: 420
              sources:
              - secret:
                  items:
                  - key: ca.crt
                    mode: 384
                    path: ca.crt
                  name: sslrootcert-secret
              - secret:
                  items:
                  - key: user.key
                    mode: 384
                    path: user.key
                  name: sslkey-user-secret
              - secret:
                  items:
                  - key: user.crt
                    mode: 384
                    path: user.crt
                  name: sslcert-user-secret
```
