### ISSUE TITLE
Usage statistics using Micrometer and Prometheus

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#293]
Hello,

We have Prometheus and Grafana running on EKS in monitoring namespace while we have shinyproxy running in a separate namespace. We are looking to implement the usage statistics using micrometer and push the metrics in the already running.
As per the documentation, we need to add below for the configuration:

scrape_configs:
  - job_name: 'shinyproxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9090'] 
But in our case, I dont think this will be valid since we have prometheus running in the different namespace and we have a URL for the same as well.
Can you please let me know what should be replaced in place of target here? should it be the service for shinyproxy which is running the namespace?
Please note I am running shinyproxy operator and shinyproxy 2.5.0

**Comment by LEDfan** [comment]
Hi

Since the operator dynamically generates ShinyProxy servers, it is impossible to hard-code the target in the scrape config of Prometheus. Therefore, you need to configure some way to autodiscover the ShinyProxy servers.  We use the following configuration for this:
```
- job_name: 'shinyproxy_apps'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
       - mynamespace
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_openanalytics_eu_sp_proxied_app]
    regex: "true"
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_openanalytics_eu_sp_spec_id]
    target_label: sp_spec_id
  - source_labels: [__meta_kubernetes_pod_annotation_openanalytics_eu_sp_realm_id]
    target_label: sp_realm_id
  - source_labels: [__meta_kubernetes_pod_annotation_openanalytics_eu_sp_user_id]
    target_label: sp_user_id
  - source_labels: [__meta_kubernetes_pod_annotation_openanalytics_eu_sp_proxy_id]
    target_label: sp_proxy_id
  - source_labels: [__meta_kubernetes_namespace]
    target_label: sp_kube_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: sp_pod_name
  - source_labels: [__meta_kubernetes_pod_container_name]
    target_label: sp_container_name
- job_name: 'shinyproxy'
  metrics_path: '/actuator/prometheus'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
       - mynamespace
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    regex: shinyproxy
    action: keep
  - source_labels: [__meta_kubernetes_pod_label_openanalytics_eu_sp_resource_name]
    target_label: sp_realm_id
  - source_labels: [__meta_kubernetes_namespace]
    target_label: sp_kube_namespace
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    regex: actuator
    action: keep
```

Note that you'll have to give Prometheus permission (using Kubernetes RBAC) to use the Kube API for retrieving pods.
