### ISSUE TITLE
 shinyproxy LDAP Role based authentication possible 

### ISSUE THREAD

**Issue by jino-varghese** [openanalytics/shinyproxy#298]
Hello Team,

Do we have an option to make AD Group-based access can provide to each application within Shiny proxy? 
If I have 5 applications in ShinyProxy, can I restrict each application based on the AD group? 

Thank You ,
Jino.

**Comment by LEDfan** [comment]
Hi

Yes, this is possible. As you can see in the [documentation](https://shinyproxy.io/documentation/configuration/#example-active-directory) you'll have to provide a `group-search-filter` and `group-search-base` which tell ShinyProxy how to parse the groups out of the LDAP information (https://shinyproxy.io/documentation/configuration/#ldap). This configuration depends on your configuration of LDAP.

**Comment by jino-varghese** [comment]
Thank you, Yes this document shows the LDAP group can access / login to the Shiny Proxy, but can we able to restrict  people to access application within the proxy using this group ?  
I saw Simple authentication method : groups: scientists ;   access-groups: [scientists], 
Those who are all belogs to this group - scientists - can access to that applicaion. like wise do we have an option in LDAP  - AD group ?

**Comment by LEDfan** [comment]
You can use the same configuration options (i.e. `access-groups`) for LDAP. Here is a full example with a public LDAP server:

```yaml
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  authentication: ldap
  admin-groups: scientists
  ldap:
    url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-base:
    group-search-filter: (uniqueMember={0})
    manager-dn: cn=read-only-admin,dc=example,dc=com
    manager-password: password
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: scientists
```

Try running this example. You can login with username `gauss` and password `password`, you'll see only the `Hello Application`. Then you can try logging in with `tesla` and `password` and you'll see both apps.
