### ISSUE TITLE
secure cookies with webservice auth

### ISSUE THREAD

**Issue by nbbn** [openanalytics/shinyproxy#301]
Hi,
I try to use secure flag on cookies set by Shinyproxy.
In general, I just add to my existing, working config:
```
server:
  secureCookies: true
```

AFAIK, it should not influence Shinyproxy working without ssl proxy (this flag should then be ignored by browser).

I tested this flag on shinyproxy without any proxy in front of it, and the flag is present.
However, I have problem with logging in. I receive no error message about invalid username/password.
My auth is set like:
```
  authentication: webservice
  webservice:
    authentication-url: "${AUTH_API_URL}/auth"
    authentication-request-body: '{"login": "%s", "password": "%s"}'
```
And I don't even see auth attempt in log of auth api.

Removal of `secureCookies` fix the problem and auth works as expected.
