### ISSUE TITLE
shinyproxy whitescreen after page reload

### ISSUE THREAD

**Issue by alex-d13** [openanalytics/shinyproxy#306]
Hi,

I am having issues with shinyproxy:
When my container is started and running and I reload the browser page, I get a whitescreen (in the network console: error 503; service not availabe). Then after 6s (I reduced the heartbeat to 6000), after the container is released due to inactivity and I reload the page again, a new container is started.
Is there a way to connect to the original container, without having to wait for 6s until the container was released and a new one is started?

Here is my application.yml

```
proxy:
  port: 8080
  landing-page: /app/namco
  authentication: none
  admin-groups: admins
  container-log-path: ./container-logs
  container-backend: docker
  container-wait-time: 10000
  heartbeat-rate: 1000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 6000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  hide-navbar: true
  users:
  - name: jack
    password: password
    groups: admins
  docker:
    internal-networking: true
  specs:
  - id: namco
    display-name: Namco
    description: Webapp for analysis of microbiome data
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    #container-cmd: ["/usr/bin/shiny-server.sh"]
    container-network: namco_sp-net
    container-image: namco

logging:
  file:
    name: ./shinyproxy.log

server:
  useForwardHeaders: true
```

and my nginx.conf

```
events {}
http {

    upstream namco {
    server shinyproxy:8080;
    }

    server {

    listen 80;
    server_name  localhost;

    underscores_in_headers on;


    location / {
        proxy_pass          http://namco;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600s;

        proxy_redirect    off;
        proxy_set_header  Host             $http_host;
        proxy_set_header  X-Real-IP        $remote_addr;
        proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Protocol $scheme;
    }
    }


}

```

Does anyone have an idea what is going on here?

Cheers,
Alex
