### ISSUE TITLE
Authentication taking too long (+-40 secs) in login page

### ISSUE THREAD

**Issue by PauloJhonny** [openanalytics/shinyproxy#308]
Hi,

I'm using shinyproxy 2.5.0 and LDAP authentication. 

Sometimes when I try to login it takes about 40 seconds. It only returns to normal time when I restart the shinyproxy service.

I'm trying to figure out the exact time this happens again after restarting the shinyproxy service.

I couldn't find in the log file what could be happening. Also, when we were using shinyproxy version 2.3.0 this never happened.

Do you have any idea how to solve this problem?

Thank you so much!

**Comment by LEDfan** [comment]
Hi

I never experienced this problem myself and don't really have a clue what could cause this. You could enable more verbose logging for the ldap component using:

```yaml
logging:
  level:
    org:
      springframework:
        security:
          ldap: DEBUG
```

Maybe that will give a useful error/debug message.
