### ISSUE TITLE
forward-headers-strategy: native keeps redirect to http instead of https

### ISSUE THREAD

**Issue by nbbn** [openanalytics/shinyproxy#318]
Hi,
as you can see from other issues opened, I try to harden my shinyproxy instance.

I have it behind reverse proxy with https termination.
However, when I do:
```
curl https://example.com -v
```
I get a response with: `Location: http://example.com/login`. I would like to have https in this response to avoid potential downgrade to http.

According to [docs](https://www.shinyproxy.io/documentation/security/#forward-headers), I tried in server section of my config:
```
server:
  servlet.session.timeout: ...
  forward-headers-strategy: native
  secureCookies: true
```

At the same time I have nginx configured exactly like in https://www.shinyproxy.io/documentation/security/#https-ssl--tls
Without any effect. Do I miss something?
Thanks
Jakub

**Comment by LEDfan** [comment]
Hi @nbbn 

The setup you describe should work. Just to be sure: is the config you provided placed at the top level of the configuration file? I.e. the `server:` is no located under another property. It should be like:

```yaml
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: ldap
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientist
 # ...
server:
  servlet.session.timeout: ...
  forward-headers-strategy: native
  secureCookies: true
```

not:

```yaml
proxy:
  server:
    servlet.session.timeout: ...
    forward-headers-strategy: native
    secureCookies: true
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: ldap
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientist
 # ...
```

If that's okay, I suspect that (for whatever reason) the proxy isn't sending the correct headers. You could try enable [request dumping](https://www.shinyproxy.io/documentation/configuration/#request-dumping) in ShinyProxy to see what headers are sent to ShinyProxy.

**Comment by nbbn** [comment]
Hi, thanks for your reply.
First of all, I checked headers with request dumping:
```
curl https://example.com -v
```
gives me:
```
shinyproxy_1  | ----------------------------REQUEST---------------------------
shinyproxy_1  |                URI=/
shinyproxy_1  |  characterEncoding=null
shinyproxy_1  |      contentLength=-1
shinyproxy_1  |        contentType=null
shinyproxy_1  |             header=X-Real-IP=192.168.xxx
shinyproxy_1  |             header=Connection=upgrade
shinyproxy_1  |             header=accept=*/*
shinyproxy_1  |             header=X-Forwarded-Protocol=https
shinyproxy_1  |             header=X-Forwarded-For=192.168.xxx
shinyproxy_1  |             header=user-agent=curl/7.74.0
shinyproxy_1  |             header=Host=example.com
shinyproxy_1  |             locale=[]
shinyproxy_1  |             method=GET
shinyproxy_1  |           protocol=HTTP/1.1
shinyproxy_1  |        queryString=
shinyproxy_1  |         remoteAddr=/192.168.xxx:0
shinyproxy_1  |         remoteHost=192.168.xxx
shinyproxy_1  |             scheme=http
shinyproxy_1  |               host=example.com
shinyproxy_1  |         serverPort=8080
shinyproxy_1  |           isSecure=false
shinyproxy_1  | --------------------------RESPONSE--------------------------
shinyproxy_1  |      contentLength=0
shinyproxy_1  |        contentType=null
shinyproxy_1  |             cookie=JSESSIONID=xxx; domain=null; path=/
shinyproxy_1  |             header=Expires=0
shinyproxy_1  |             header=Cache-Control=no-cache, no-store, max-age=0, must-revalidate
shinyproxy_1  |             header=Set-Cookie=JSESSIONID=xxx; path=/; secure; HttpOnly
shinyproxy_1  |             header=X-XSS-Protection=1; mode=block
shinyproxy_1  |             header=Pragma=no-cache
shinyproxy_1  |             header=Location=http://example.com/login
shinyproxy_1  |             header=Date=Tue, 24 Aug 2021 11:58:58 GMT
shinyproxy_1  |             header=Connection=keep-alive
shinyproxy_1  |             header=X-Content-Type-Options=nosniff
shinyproxy_1  |             header=Content-Length=0
shinyproxy_1  |             status=302

```

my application.yml is like (I removed some sensible elements):
```
proxy:
  title:
  favicon-path: favicon.png
  logo-url: xxx
  landing-page: /app/application
  heartbeat-rate: xxx
  heartbeat-timeout: xxx
  container-wait-time: xxx
  template-path: ./templates/xxx
  port: 8080
  authentication: webservice
  webservice:
    authentication-url: "xxx"
    authentication-request-body: '{"login": "%s", "password": "%s"}'
  docker:
    internal-networking: true
  specs:
  - id: application
    display-name: "xxx"
    description: xxx
    container-image: "xxx"
    container-network: "xxx"
    container-volumes: ["xxx"]
    container-env:
      APP_IMAGE: xxx


server:
  servlet.session.timeout: xxx
  forward-headers-strategy: native
  secureCookies: true

logging:
  file:
    shinyproxy.log
  requestdump: true
```
