### ISSUE TITLE
Preinitialize the container

### ISSUE THREAD

**Issue by vanhry** [openanalytics/shinyproxy#322]
I deployed a quite large shiny application with shinyproxy, but the launching time is extremely slow (7-10 sec). On the other side, when user open app served by shiny-server, the app is already running, and it launches very fast (it’s obvious because there is no need to initialization).
But my question is can we make some “prepared container” (we start it allocated the port, but don’t give it to the user), namely always keep “a ready for start container” for user, and when user opens app, then we create the new one for the next user. I think it can help to prevent slow launching but I don’t know if it is possible. 
I will appreciate any help from your side.

**Comment by etschste** [comment]
I would very much appreciate this feature too. It's even worse with Quarto/shiny rendered pages. In my case it takes about 25 seconds till the container and the page is up, with an already started container the response is instant (under 0.5 seconds).

**Comment by tvelsberg** [comment]
Would love to see such feature!
We have facing load times up-to 30 secs for some rather heavy applications running in K8s. Most of the instances are identical. So having a pool of pre-started containers would be really great.

**Comment by luayaswad** [comment]
I would love to see this feature too.

**Comment by bartekch** [comment]
I would really appreciate this feature, it would be a game changer for me.

**Comment by bioinfomagician** [comment]
I also agree that this would be a great enhancement to shinyproxy

**Comment by kramerrs** [comment]
I don't know if pre-nitialization is really the solution.  I currently have a 20-25 second start time.  The thing is that I can launch the container in docker in less than three seconds.  I can also time each step, during the app start loading libraries connecting to the database processing the data are all negligible.  However from the ShinyProxy logs it is polling several times, waiting for the container to become responsive and on the app side it takes a large number of seconds for the "Listening on" ip address message to come up.  Is it a network issue?  I take it ShinyProxy is sitting their waiting to hear back, what takes Shiny so long to initialize the network connection in the container?  Is this a network issue?

**Comment by sybrohee** [comment]
Up here. 
Preloaded container could be a really nice addition.

**Comment by sybrohee** [comment]
In the support of shinyproxy, I describe a solution that, instead of preloading the container, preloads the R process (with the libs).
I would find it interesting to get your insights about the procedure.
https://support.openanalytics.eu/t/create-running-user-proxies-containers-in-advance/2521

**Comment by danielloader** [comment]
Would be nice if you could add a preload flag to an app spec, so that on successful login spins up the container at that point ready to use.

```yaml
proxy:
  specs:
    - id: 01_hello
      display-name: Hello Application
      description: Application which demonstrates the basics of a Shiny app
      container-cmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
      container-image: openanalytics/shinyproxy-demo
      access-groups: [ scientists, mathematicians ]
      preload: true
    - id: 06_tabsets
      container-cmd: [ "R", "-e", "shinyproxy::run_06_tabsets()" ]
      container-image: openanalytics/shinyproxy-demo
      access-groups: scientists
```
