### ISSUE TITLE
Not saving logs

### ISSUE THREAD

**Issue by francescocamussoni** [openanalytics/shinyproxy#325]
Hello, i'm using the .deb package for the deploy and with this application.yml (on /etc/shinyproxy/) it doesnt log container logs nor shinyproxy logs

```
proxy:
  title: GDM Analytics Team
  logo-url: https://i.imgur.com/xFU0biq.png
  favicon-path: /etc/shinyproxy/favicon.ico
  landing-page: /
  template-path: ./templates/1col
  #template-path:./templates/modified_navbar
  port: 3839
  authentication: none
  admin-groups: GDM
  container-log-path: /etc/shinyproxy/logs/containers
  # Example: 'simple' authentication configuration
  users:
  - name: guest
    password: guest
    groups: user
  - name: jclavijo
    password: gdm7030
    groups: GDM
  - name: mmoine
    password: gdm7030
    groups: GDM
  - name: lmendonca
    password: gdm7030
    groups: GDM
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 7030_vis_results
    display-name: 70/30 Results Visualization APP
    description: App to visualize and make selections in the RETEST 70/30 experiments
    container-cmd: ["R", "-e", "shiny::runApp('/root/BIBD_GS/src/r/shiny/app.R')"]
    container-image: 7030
    access-groups: GDM, user

logging:
  file:
    name: /etc/shinyproxy/logs/shinyproxy/shinyproxy.log
```

On the other hand, when I use the java -jar command, it works just fine with the same application.yml file

Any thoughts?
