### ISSUE TITLE
Implementation of Application based security groups in shinyproxy

### ISSUE THREAD

**Issue by aupadh12** [openanalytics/shinyproxy#333]
Hello,

We are using OIDC type of authentication and Azure AD is our oidc provider.
Things are working fine so far. But recently we received a request to implement Group-based authorization for individual applications.
I am trying to follow the documentation for this purpose but there is no reference of using Azure AD for creating roles-claim which is necessary. 
Can we get the steps needed to integrate Azure AD oidc provider for group based authorization.
We already have AD group ready which needs to be applied as access-groups for the applications running on shinyproxy.

**Comment by LEDfan** [comment]
Hi

The main step you need to take is to configure a claim that contains the AD group. The exact procedure for this depends on the configuration of Azure AD. The documentation of MS should help with this: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-enterprise-app-role-management .
Typically this is handled by the team that manages (Azure) AD, since they know how their setup works.

The next step is to configure ShinyProxy to use this claim for the group authorization. This can be done using the `proxy.openid.roles-claim` property of ShinyProxy. You just have to fill in the name of the claim you created in step one.

Hope this helps.

**Comment by ndsP95** [comment]
Hi

I'm having the same issue as @aupadh12. Everything is working fine with OIDC authentication and Azure AD as the provider, but I'm failing to implement group-based access on the application level. It would be helpful to have a guide explaining the process of configuring a claim for a Azure AD Registered Application, and how to link it to the `proxy.openid.roles-claim` of ShinyProxy.

**Comment by aupadh12** [comment]
Hi @ndsP95 ,

The issue with me was the way in which I was passing access-groups.
Can you may be give an example of the yaml file where you are setting the configurations?
Also, it would be good to understand whether the variable openanalytics.eu/sp-user-groups has the AD groups which you are part of by running kubectl get pods <pod-name> -n <namespace> -o yaml

**Comment by ndsP95** [comment]
I'm not using kubernetes to deploy ShinyProxy. I have tried creating app roles using the manifest, and setting the access groups to the names of these roles (in the App Registrations blade). I have also tried assigning several groups (in the Enterprise Applications blade), but I'm unsure what to pass in the `proxy.openid.roles-claim` setting of the application.yml. How did you set up the roles/groups in your application, and what did you set in the roles-claim and access-groups fields?

**Comment by LEDfan** [comment]
Hi @cheetm 

These kind of role claims is not supported by ShinyProxy. Your claim needs to be a JSON array containing strings (i.e. no objects). Then you need to specify the name of the claim as `proxy.openid.roles-claim` property in ShinyProxy.

**Comment by techcental17** [comment]
has anyone gotten the groups to work im on the same boat some help with example would be helpful

**Comment by LEDfan** [comment]
Hi @techcental17 , please have a look at the new FAQ entry: https://shinyproxy.io/faq/#debugging-group-access-when-using-openid  This should help!

**Comment by techcental17** [comment]
@LEDfan do you have any example yml ?

**Comment by LEDfan** [comment]
You could use the following yaml file as a basis for your configuration:

```yaml
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: openid
  openid:
    auth-url: https://login.microsoftonline.com/<your-tenant-id>/oauth2/authorize
    token-url: https://login.microsoftonline.com/<your-tenant-id>/oauth2/token
    jwks-url: https://login.microsoftonline.com/common/discovery/keys
    client-id: ***
    client-secret: ***
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: scientists
logging:
  level:
    eu:
      openanalytics:
        containerproxy:
          auth: DEBUG
```
