### ISSUE TITLE
User Group specific settings

### ISSUE THREAD

**Issue by FGG-Belfast** [openanalytics/shinyproxy#338]
Not sure if this is a popular request, but I think it would be useful if you could change settings based on user groups. For example an admin/paid user group can have 5 instances of an app running at once whereas a basic user could only have 1.

This could also be used for other settings such as how long the containers stay active, memory to allocate and so on.

Thanks.

**Comment by LEDfan** [comment]
Hi, thanks for your request.

I'm not sure if this is a popular request, but I understand the use-case of it. Currently there is no official method for it, but there are two way how you can implement this:

1. by duplicating your app specifications for each group. For example:
```yaml
  - id: 01_hello_basic
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [basic_tier]
   max-instances: 1
  - id: 01_hello_paid
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [paid_tier]
   max-instances: 5
```

This way the `01_hello_basic` app is only be shown to members of the `basic_tier` group and the `01_hello_paid` is only shown to members of the `01_hello_paid` group. You can create as many "duplicate" apps as you need, for the end-user only one app is shown. I think this is the easiest workaround, but the configuration can become a bit long of course.

2. by using [SpEL](https://shinyproxy.io/documentation/spel/). Most fields in the configuration have support for SpEL. For example for the `container-memory` field:

```yaml
  - id: 01_hello_basic
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-memory-limit: "#{groups.contains('LARGE_TIER') ? '2G' : (groups.contains('MEDIUM_TIER') ? '1G' : '512M')}"
```

If the user is part of the `LARGE_TIER` group they get 2 gigabyte memory, if they are part of the `MEDIUM_TIER` they get 1 gigabyte and otherwise they get 512 megabyte. 

Unfortunately, at the time of writing, the `max-instances` field does not support SpEL. However, I think it would be good if the field supported it, so I will try to add it in the next release (and keep this issue open for this enhancement).

Looking forward to what you think!
