### ISSUE TITLE
InResponseToField of the Response doesn't correspond to sent message | SP - 2.6.0

### ISSUE THREAD

**Issue by templary** [openanalytics/shinyproxy#342]
Hello, 

I'm encountering a strange variant of SAMLException
I'm getting this error
`e.o.containerproxy.service.UserService   : Authentication failure [user: ] [error: Error validating SAML message]`
`org.opensaml.common.SAMLException: InResponseToField of the Response doesn't correspond to sent message XXXXXX`

Error is the same as in the case of:
https://github.com/openanalytics/shinyproxy/issues/335

I tried to solve it using the suggested procedure in the documentation

```
server:
  secure-cookies: true
proxy:
  same-site-cookie: None

```

The problem is that if I run the application in Safari or Firefox without using the above configuration login works as it should. But it doesn't work in Chrome.

If I add the config, the login works in Chrome but not in Safari and Firefox.

ShinyProxy version - 2.6.0

SAML in YML

```
  saml:
    idp-metadata-url: https://XXXXXX.eu.auth0.com/samlp/metadata/XXXXXX
    app-entity-id: urn:XXXXXX.eu.auth0.com
    app-base-url: http://localhost:8080
    name-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
    roles-attribute: http://schemas.auth0.com/roles
    logout-url: https://XXXXXX.eu.auth0.com/v2/logout?client_id=XXXXXX&returnTo=http://localhost:8080
    nameidentifier-attribute: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
    email-verified-attribute: http://schemas.auth0.com/email_verified
    created-at-attribute: http://schemas.auth0.com/created_at
    lb-server-name: localhost:8080
    lb-scheme: http
```
