### ISSUE TITLE
OpenShift and Prometheus

### ISSUE THREAD

**Issue by panoptikum** [openanalytics/shinyproxy#344]
Dear Shinyproxy Community,

I'm looking into using the shinyproxy metrics in Prometheus which is already provided by OpenShift. Our cluster is not mainly administrated by me, but I was hoping that I can simply expose the metrics to the existing Prometheus instance? For example I can see the cpu, memory usage per pod in the internal monitoring tool of OpenShift. The documentation of OpenShift says that it is possible to add custom metrics/services to the monitoring as well. Unfortunately, I don't really know where to start and how to implement this. Any hints would be much appreciated.

Best,
Felix

**Comment by LEDfan** [comment]
Hi

As a first step you have to enable metrics in ShinyProxy: https://shinyproxy.io/documentation/usage-statistics/#configuration-2 
Then you need to modify the ShinyProxy `service` resource to include the `actuator` port, it should look something like:

```yaml

kind: Service
apiVersion: v1
metadata:
  name: shinyproxy
spec:
  type: ClusterIP # could be nodeport 
  selector:
    app: shinyproxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 9090
    targetPort: 9090
```

The next step is to tell OpenShift to scrape your ShinyProxy server. You can follow this guide https://docs.openshift.com/container-platform/4.6/monitoring/managing-metrics.html#specifying-how-a-service-is-monitored_managing-metrics 
The ServiceMonitor should look something like:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-shinyproxy-monitor
  name: prometheus-shinyproxy-monitor
  namespace: <your-shinyproxy-namespace>
spec:
  endpoints:
  - interval: 30s
    port: 9090
    scheme: http
   path: /actuator/prometheus
  selector:
    matchLabels:
      app: shinyproxy
```
