### ISSUE TITLE
PWA support with ShinyProxy

### ISSUE THREAD

**Issue by hcstubbe** [openanalytics/shinyproxy#347]
I am trying to host a [shinyMobile app](https://rinterface.github.io/shinyMobile/) with [progressive web app](https://en.wikipedia.org/wiki/Progressive_web_application) support on the most recent version of ShinyProxy (2.6.0). However, PWA seems to be not supported.
Is it possible to host this app using PWA? If not, will there be PWA support in future versions?

Thank you!

**Comment by LEDfan** [comment]
Hi

I did some tests with shinyMobile and the PWA support in ShinyProxy. I used this app https://github.com/RinteRface/shinyMobile/tree/master/inst/examples/gallery . What I observed:

 - when opening the app through the standard ShinyProxy method (i.e. using the `/app`) endpoint, the app is loaded in an iframe, therefore a browser is unable to find the PWA manifest. (you can still add it as a PWA, but it won't use the properties inside the manifest).
 - you can open the app using the `/app_direct/<my_app_id>` endpoint, in this case a browser is able to find the manfiest and you can add it as a proper PWA app.
 - the problem is however, that once your session is expired and you try to re-login, you (could) end up on the main page of ShinyProxy and not on the app itself.
 -  another problem is that you don't see a loading screen, but just a white screen until the app loads.

In order to solve this, the manifest should be exposed by ShinyProxy, rather than inside the app. Currently we don't have an official way to do this. However, using the template mechanism you can achieve this (https://github.com/openanalytics/shinyproxy-config-examples/tree/master/04-custom-html-template)

First create a new `app.html` template. Next in the `<head>` section add the following code:

```html
	<th:block th:if="${appName == 'pwa-demo'}">
		<link rel="manifest" th:href="@{/assets/manifest.webmanifest}">
	</th:block>
```

The if statement is needed to prevent the manifest being exposed for other apps. You can add this block multiple times (one for each app).

Next create a directory `assets` in your templates folder and add the pwa manifest of the app in the folder. For the example app, I'm using (based on https://github.com/RinteRface/shinyMobile/blob/master/inst/examples/gallery/www/manifest.webmanifest):

```json
{
  "name": "My Progressive Web App",
  "short_name": "My App 2",
  "description": "What it does!",
  "lang": "en-US",
  "start_url": "/app/pwa-demo",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#ffffff",
  "icons": [
    {
      "src": "/assets/icons/icon-144.png",
      "sizes": "144x144"
    }
  ]
}
```

Notice that I changed the `start_url` to `/app/-pwa-demo` and also the path to the icon. You can create a directory `icons` in the `assets` folder an place your icon there.

Although this requires a bit more work from your end, this is working fine for me. All ShinyProxy features are supported (i.e. navbar/iframe), login is properly working etc.

We might improve the support for PWAs in the future, so that you have less manual steps to do. We are still thinking about the proper solution here, because we want the support to be flexible. For example, it might make sense to allow for some additional properties to be set (like regular app icons etc). 
If someone is interested in this feature, please upvote this issue, this way we can estimate the interest. In addition,  any feedback on how this should be implemented (mainly how you want to use it) is welcome.

**Comment by hcstubbe** [comment]
Thank you so much for your reply! I have been trying to get this to work all night, but it won't. I am using ShinyProxy 2.6.0 on docker. I configured the ShinyProxy as you described above and used the same app. Running the app on shiny server works. But on ShinyProxy, the web manifest cannot be found. Do you have any idea, what could be the reason for this?

Thank you so much for your help!
Hans


With /app_direct/test_app:
![grafik](https://user-images.githubusercontent.com/48794922/152477069-142a0e0c-49d4-41d8-8f5b-1e49636aee05.png)

With changed template and /app/test_app:
![grafik](https://user-images.githubusercontent.com/48794922/152477208-5931eb9b-d6c6-40c3-9fb9-2384feef3023.png)


I use this code to for docker-compose:
```
version: '3.5'

services:
                              
  shinyproxy:
    image: hstubbe/shp:latest
    ports:
      - 8080:8080
    networks:
      - sp-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
    volumes:
      - ./application/application_test.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  sp-net:
    external: true


```


This is my application file:
```
proxy:
  title: Test Server
  port: 8080 
  template-path: ./templates/test
 
  authentication: none
  admin-groups: adminecrf
  users:
  - name: admin
    password: admin
    groups: admin
  
  container-backend: docker 
  
  docker:
      internal-networking: true
  

  specs:
  - id: test_app
    display-name: test_app
    description: test_app
    container-image: test_app
    container-network: sp-net
    access-groups: admin

    
logging:
  file:
    shinyproxy.log
    

server:
  forward-headers-strategy:
    native
```


And the following is the app.html:
```
<head lang="en">
	<title th:text="${appTitle} + ' - ' + ${appInstanceDisplayName}"></title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" media="screen" th:href="@{${bootstrapCss}}" />
	<link rel="stylesheet" media="screen" th:href="@{/css/default.css}"/>
	<script th:src="@{${jqueryJs}}"></script>
	<script th:src="@{${bootstrapJs}}"></script>
	<script th:src="@{${handlebars}}"></script>
	<script th:src="@{${cookieJs}}"></script>
	<script th:src="@{/js/shiny.app.js}"></script>
	<script th:src="@{/js/shiny.api.js}"></script>
	<script th:src="@{/js/shiny.connections.js}"></script>
	<script th:src="@{/js/shiny.instances.js}"></script>
	<script th:src="@{/js/shiny.ui.js}"></script>
	<script th:src="@{/js/shiny.common.js}"></script>
	<script th:if="${operatorEnabled}" th:src="@{/js/shiny.operator.js}"></script>
	<script th:src="@{/handlebars/precompiled.js}"></script>
	<th:block th:if="${appName == 'lcarsm'}">
		<link rel="manifest" th:href="@{/assets/manifest.webmanifest}">
	</th:block>
</head>
```
