### ISSUE TITLE
SAML 2.0 with okta - redirect loop

### ISSUE THREAD

**Issue by wtarnawski** [openanalytics/shinyproxy#349]
Hi,

I'm setting up the shinyproxy with saml authentication. When I go to the app I get in a redirect loop between a page _https://okta.com/app/.../sso/saml/_ and the _https://servername.org/saml/SSO_ endpoint on my server.

The shinyproxy runs behind a httpd reverse proxy behind a load balancer. My best shot is that's the cause of the problem.
Also: the SSL cert is self signed, but my intuition is that's not a problem.

I verified the setup works with simple authentication, but not with SAML.

Reverse proxy (httpd 2.4.6-97.el7_9.4 on centos 7):
```
<VirtualHost *:80>
  ServerName servername.org

  RewriteEngine On

  RewriteCond %{SERVER_NAME} =servername.org
  RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]

</VirtualHost>

<VirtualHost *:443>
  DocumentRoot "/srv/shinyproxy"
  ServerName servername.org
  ServerAlias servername.org

  RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}e
  RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}e
  RemoteIPHeader X-Forwarded-For

  ProxyRequests Off
  ProxyPreserveHost On
  ProxyPass / http://app_server.org:8080/
  ProxyPassReverse / http://app_server.org:8080/

  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} =websocket
  RewriteRule /(.*) ws://app_server.org:8080/$1 [P,L]

  SSLEngine on
  SSLCertificateFile /etc/httpd/conf.d/new_ssl/server.crt
  SSLCertificateKeyFile /etc/httpd/conf.d/new_ssl/server.key

</VirtualHost>

```

Shinyproxy (shinyproxy_2.6.0_x86_64, on centos 7):
```
server:
  secure-cookies: true
  forward-headers-strategy: native
  use-forward-headers: true
proxy:
  title: Open Analytics Shiny Proxy
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-log-path: ./container-logs
  authentication: saml
  saml:
    idp-metadata-url: https://orgname.okta.com/app/.../sso/saml/metadata
    app-entity-id: https://servername.org/saml/metadata
    app-base-url:  https://servername.org/app
    name-attribute: user_email
    roles-attribute: groups_shiny_asd
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
 logging:
  file:
    name: shinyproxy.log
  requestdump: true

```

okta saml settings
```
Single Sign On URL
https://servername.org/saml/SSO
Recipient URL
https://servername.org/saml/SSO
Destination URL
https://servername.org/saml/SSO
Audience Restriction
https://servername.org/saml/metadata
Default Relay State
/
Name ID Format
Unspecified
Response
Signed
Assertion Signature
Signed
Signature Algorithm
RSA_SHA256
Digest Algorithm
SHA256
Assertion Encryption
Unencrypted
SAML Single Logout
Disabled
authnContextClassRef
PasswordProtectedTransport
Honor Force Authentication
Yes
Assertion Inline Hook
None (disabled)
SAML Issuer ID
http://www.okta.com/${org.externalKey}

```
Can you please help me troubleshoot this?

Also: I had to guess and try some of the values as I didn't find a guide to set up shinyproxy with okta SAML. Would it be possible for you to write such guide?

**Comment by LEDfan** [comment]
Hi

At first I don't see any issues in your configuration. Can you check the logs of ShinyProxy? Typically when you have such a redirect issue, it means that Okta correctly authenticates the user, but that ShinyProxy does not accept the assertion (saml credentials). In that case ShinyProxy should log some information.

**Comment by wtarnawski** [comment]
Hi again,

thank you for your reply.

I noticed that the shinyproxy doesn't log anything on my server. It turns out I had to create a file `/var/log/shinyproxy.log` and assign the shinyproxy unix user to it. As someone who sets this up, I would assume the server should not work until you create this file and make it accessible to the shinyproxy unix user, or even set it up for you if that's possible - should I file a bug report on this?

Anyway, when logging started working properly, I inspected the logs and found that message:
`Caused by: java.net.MalformedURLException: no protocol: expr=(null)://servername.org/saml/SSO`

So I figured out that I need to set up the load balancer in shinyproxy as it's not setting up the scheme properly. I added these lines to the application.yml:

    lb-server-name: servername.org
    lb-context-path: /
    lb-port-in-url: false
    lb-scheme: "https"
    lb-server-port: 443

Now it's not a redirect loop anymore, but I get a long error site
```

Error
Status code: 200

Message: Error validating SAML message
<lots of stuff>
Caused by: org.opensaml.common.SAMLException: InResponseToField of the Response doesn't correspond to sent message a1ae7iaid9656113ffib35g5ede06d
<more stuff>
```

In SAMLTracer I found that when logging in, the shinyproxy sends a SAML request like this
```
<saml2p:AuthnRequest xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                     AssertionConsumerServiceURL="https://servername.org/saml/SSO"
                     Destination="https://okta.com/app/.../sso/saml/"
                     ForceAuthn="false"
                     ID="a1ae7iaid9656113ffib35g5ede06d"
                     IsPassive="false"
                     IssueInstant="2022-02-24T11:03:41.661Z"
                     ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                     Version="2.0"
                     >
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://servername.org/saml/metadata</saml2:Issuer>
</saml2p:AuthnRequest>
```

And the response looks like:
```
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 Destination="https://servername.org/saml/SSO"
                 ID="id20806169914911443884689874"
                 InResponseTo="a1ae7iaid9656113ffib35g5ede06d"
                 IssueInstant="2022-02-24T11:04:21.683Z"
                 Version="2.0"
                 >
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                  Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                  >http://www.okta.com/....................</saml2:Issuer>
< more lines including groups, username and other attributes, seems to be properly formed, please let me know if you want to see them >
```

I can see that request ID and response InResponseTo fields match. But I can see it's called "InResponseToField" in the error message. Could this be an issue?

**Comment by wtarnawski** [comment]
> How did you install ShinyProxy? (RPM, DEB package, manual etc)

I installed it with 
yum install https://www.shinyproxy.io/downloads/shinyproxy_2.6.0_x86_64.rpm -y
I followed the instructions from https://shinyproxy.io/documentation/getting-started/

> This error is typically caused because an issue with the same-site-cookie policy. Please check https://shinyproxy.io/documentation/configuration/#samesitecookies-and-saml .

I can't believe I missed that! Setting these accordingly fixed my problem. Thank you for your support!

My final config, for future generations:

```
server:
  secure-cookies: true
  forward-headers-strategy: native
  use-forward-headers: true
proxy:
  title: Open Analytics Shiny Proxy
  #logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  container-log-path: ./container-logs
  same-site-cookie: none
  authentication: saml
  saml:
    idp-metadata-url: https://orgname.okta.com/app/.../sso/saml/metadata
    app-entity-id: https://servername.org/saml/metadata
    app-base-url:  https://servername.org
    name-attribute: user_email
    roles-attribute: groups_shiny_asd
    lb-server-name: servername.org
    lb-context-path: /
    lb-port-in-url: false
    lb-scheme: "https"
    lb-server-port: 443
  # Example: 'simple' authentication configuration
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians, mygroup]
logging:
  file:
    name: /var/log/shinyproxy.log
  requestdump: true
  level:
    root: ERROR
```

Httpd reverse proxy config stays the same, save for lines
```
  RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}e
  RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}e
  RemoteIPHeader X-Forwarded-For
```
which I removed.

Okta config didn't change from my first post, so I'm omitting that.

Again: thank you very much!
