### ISSUE TITLE
Docker volume not working with container-specs: volumes: option

### ISSUE THREAD

**Issue by wtarnawski** [openanalytics/shinyproxy#355]
Hi,

I'm trying to write an empty file into a volume. I have this app csvtest_container that's created with a dockerfile:

```
# Base image https://hub.docker.com/u/rocker/
FROM rocker/r-base:latest

# system libraries of general use
#setup happens here
...
WORKDIR /home/app
COPY . /home/app

# expose port
EXPOSE 3838

RUN touch /home/app/data/test
```

and the sole purpose of this app is to write an empty file at /home/app/data/test. It also has a simple shiny app so that shinyproxy can run, so I have a confirmation that the container was run. 

When I use this docker command
 `docker run -v csvtest_volume:/home/app/data --rm csvtest_container`
 to run this container and mount to a specific volume, it puts the "test" empty file into the volume directory (/var/lib/docker/volumes/csvtest_volume/_data) as intended. But when I use shinyproxy with this setup
```
  - id: csvtest
    display-name: csvapp_display_name
    container-cmd: ["R", "-e", "shiny::runApp('/home/app')"]
    container-image: csvtest_container
    access-groups: [group1]
    container-privileged: true
    container-specs:
      volumes: [ "/var/lib/docker/volumes/csvtest_volume/_data:/home/app/data" ]
```
and launch the app in the browser it doesn't create the "test" file inside "/var/lib/docker/volumes/csvtest_volume/_data" directory. I also tried
```
volumes: [ "csvtest_volume:/home/app/data" ]
```
which also does not work as intended. Can you help me?
