### ISSUE TITLE
Oauth2 not working in shinyproxy versions 2.5.0 and above

### ISSUE THREAD

**Issue by shreyashfederer** [openanalytics/shinyproxy#370]
Hello , 

We are running shinyproxy apps on AWS EC2 instance.
We are able to run shinyproxy version 2.3.0 , 2.4.0 while using authentication method as `oauth2`.

Our oauth configuration in application.yml looks like:

``` 
oauth2:
    resource-id: https://<resource-id>
    jwks-url: https://api<jwks-url>/auth/serveJwks
```

When we update shinyproxy version from `2.3.0` to` 2.5.0` after running commands

```
sudo wget downloadproxy
unlink shinyproxy.jar
ln -s shinyproxy-2.5.0.jar shinyproxy.jar
sudo service shinyproxy restart
```

we get the following error. 

![image](https://user-images.githubusercontent.com/31564161/168561942-9f506096-fbac-4af6-bbcb-a5304922b767.png)

```
Field webSecurityConfigurerAdapter in eu.openanalytics.containerproxy.auth.impl.KeycloakAuthenticationBackend required a single bean, but 2 were found:
May 16 04:50:46 ip-172-31-73-41 java[28433]: - webSecurityConfig: defined in URL [jar:file:/opt/shinyproxy/shinyproxy-2.5.0.jar!/BOOT-INF/lib/containerproxy-0.8.8.j
May 16 04:50:46 ip-172-31-73-41 java[28433]: - org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration: defined in null

```

Attaching our application.yml file 

```
server:
  useForwardHeaders: true
proxy:

  title: <dashboard-title-here>
  logo-url: someurl
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: someadmin
  oauth2:
    resource-id: https://<resource-id>
    jwks-url: https://api<jwks-url>/auth/serveJwks
  users:
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
 
  specs:
    - id: default
      display-name: <app-name-here>
      description: <app-description-here>
      port: <port>
      container-image: <app-name-here>
      groups: someadmin , client
logging:
  file:
    shinyproxy.log
```

The same application.yaml file works for version shinyproxy version `2.3.0 `and `2.4.0` but not for `2.5.0` and above. Could someone please help us ?

Can we please add support for oauth in shinyproxy versions `2.5.0` and above ?
