### ISSUE TITLE
Container Wait Time Maxes at 60s?

### ISSUE THREAD

**Issue by nik-humphries** [openanalytics/shinyproxy#371]
We are experimenting with node pools at the moment using SP and are looking at creating app pods on it's own node pool with SP on a separate system node pool. We are trying to see if we can reasonably scale to 0 on this app node pool. It takes roughly 3-4 minutes for a node pool to create a new node when requested, so we have attempted to set the container wait time to a suitable value to wait for this.

```
apiVersion: openanalytics.eu/v1
kind: ShinyProxy
metadata:
  name: shinyproxy
spec:
  server:
    secureCookies: true
    frameOptions: sameorigin
    forward-headers-strategy: native
  spring:
    session:
      store-type: redis
      redis:
        configure-action: none
    redis:
      host: xxx
      password: xxx
  logging:
    file:
      shinyproxy.log
  proxy:
    default-webSocket-reconnection-mode: Confirm
    title: xxx
    logo-url: xxx
    template-path: xxx
    container-log-path: ./container-logs
    landingPage: /
    containerBackend: kubernetes
    container-wait-time: 200000
    kubernetes: 
      namespace: xxx
      internal-networking: true
      image-pull-policy: Always
      node-selector: worktype=xxx
    authentication: none
    admin-groups: admins

```

You can see above that we have set `container-wait-time: 200000`, expecting this to be 200 seconds. Instead we find that the pod only tries to be created for 60 seconds before we get a 500 error. Is this a hard limit set within SP or something else? I know that elsewhere we can keep pods in a scheduled state for long enough for a node to be created.
