### ISSUE TITLE
Cannot login ldap

### ISSUE THREAD

**Issue by rldmt** [openanalytics/shinyproxy#373]
Hello,
I am having trouble connecting with ldap authentication. The structure is like this. 5 users, 1 group, tw0 subgroups. The users and ou are already set up on AD.
AD:
     Mygroup:
     User1
                       subgroup1: usersub1, usersub2
                       subgroup2: usersub3, usersub4
    othergroups:
    othergroups:

current yml file

 ```
 ldap:
    url: ldap://example.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-base: 
    group-search-filter: (uniqueMember={0})
    manager-dn: ou=User1,ou=Mygroup,dc=example,dc=com
    manager-password: xxxxxx
```

It does not seem to make any connection to any of the users.

**Comment by rldmt** [comment]
Also in the documentation I see that you need to set uid={0}. I do not see any uid when looking up the ad directory. What should I put instead of uid?

**Comment by LEDfan** [comment]
Hi

The `{0}` will of `user-dn-pattern` will be replaced by the username filled in by the user.
For example, when a user tries to login with the username `jack`, ShinyProxy will search for ldap objects containing the value `jack` for the property `uid`. So if in your case you have a property `username` you have to specify:

```
   user-dn-pattern: username={0}
```

and then users should be able to login by that username.

As a tip: start without group configuration (i.e. remove the `group-search-base` and `group-search-filter` properties). It'll be easier to first make login work and only then the configuration of groups.

**Comment by rldmt** [comment]
Hello,
I already solved the issue. Sorry for late reply. I want to note that I mistakenly conflate Organizational Units (OU) and Groups which in Active Directory in my case are totally different things. Because of this assumption Groups were left in the dark meanwhile I was working with Organizational Units and therefore could not not connect properly. As soon as I created the relevant groups all I did was filter and narrow the scope of my search because AD had a lot of users and I wanted only to search to a subset. Here is my config snippet that I did use:
```
ldap:
    url: ldap://123.34.56.789:389/DC=company,DC=local
    user-search-base:  OU=HR Department
    user-search-filter: (sAMAccountName={0})
    group-search-base: OU=HR Department
    group-search-filter: (member={0})
    manager-dn: CN=userManagerDN,OU=HR Department,DC=company,DC=local
    manager-password: userManagerDNpassword
```

Thank you for your help.
