### ISSUE TITLE
Configure subdomain shinyproxy

### ISSUE THREAD

**Issue by kennedymwavu** [openanalytics/shinyproxy#375]
First things first, I'm quite a beginner at hosting shiny apps on docker and shinyproxy. The terms I use might be a bit layman and incorrect.

I have my application running well on shinyproxy and can be accessed through `serveripaddress:8080/app/01_hello`.

The problem comes when I try to use a link ie. `theapp.company.com` instead of the ip address. This is what it shows when I go to the link:

![image](https://user-images.githubusercontent.com/65233968/176400702-b8520425-07aa-4b6a-a617-da69641ab42b.png)

Here is the necessary part of `01_hello` nginx configuration file:

```
   location / {
       proxy_pass          http://localhost:8080/app/01_hello;

       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_read_timeout 600s;

       proxy_redirect    off;
       proxy_set_header  Host              $http_host;
       proxy_set_header  X-Real-IP         $remote_addr;
       proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
       proxy_set_header  X-Forwarded-Proto $scheme;
   }

```

But when I change the proxy_pass to:

```
proxy_pass          http://localhost:8080;
```

then I can go to `theapp.company.com/app/01_hello` which works, but not what I want.

I just want it to be `theapp.company.com`. How do I achieve this?

**Comment by nrarnt** [comment]
Kennedy, it could be a problem with you application.yml file.
Could you post a snippet of it to help debug?

**Comment by kennedymwavu** [comment]
Hi @nrarnt , 

Here is a snippet of how my application.yml file looks like:

```yaml
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: none
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  # Example: 'ldap' authentication configuration
  ldap:
    url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-base:
    group-search-filter: (uniqueMember={0})
    manager-dn: cn=read-only-admin,dc=example,dc=com
    manager-password: password
    # Docker configuration
  docker:
    url: http://127.0.0.1:2375
    port-range-start: 20000
  specs:
  - id: example-app
    display-name: example-app
    description: My example App
    container-cmd: ["R", "-e", "shiny::runApp('/root/example-app')"]
    container-image: examples/example-app
    container-env-file: /home/kennedy/rshinyapps/example-app/.Renviron
    access-groups: scientists

logging:
  file:
    shinyproxy.log

```
