### ISSUE TITLE
Feature request: use secret for LDAP password

### ISSUE THREAD

**Issue by gbavoz1** [openanalytics/shinyproxy#384]
Currently, `specs.ldap.manager-password` needs to be spelled out in the `Shinyproxy` object to connect to an LDAP/AD provider. Since we want our users to be able to self-manage their proxies we are now forced to expose that password (we are working on an helm chart that combines multiple values files, taking input from developers just for the `spec.specs` portion). It would be very beneficial if we could refer to that field as a Kubernetes secret like:

```
manager-password:
  valueFrom:
    secretKeyRef:
      key: ldap-password
      name: ldap-secret
```
