### ISSUE TITLE
Multiple LDAP does not work as a backup

### ISSUE THREAD

**Issue by feddelegrand7** [openanalytics/shinyproxy#396]
Hello, 

I'm trying to use multiple LDAP as follows: 
```
authentication: ldap
  admin-groups: ............"
  container-wait-time: 600000
  ldap:
  -  url: first_ldap_url
     user-search-base: OU=Users
     user-search-filter: (sAMAccountName={0})
     group-search-base: OU=Groups
     group-search-filter: (member={0})
     manager-dn: ......................
     manager-password: "........................"
  -  url: second
     user-search-base:
     user-search-filter: (sAMAccountName={0})
     group-search-base: OU=Groups
     group-search-filter: (member={0})
     manager-dn: ..........................................
     manager-password: "..................."
```
I was expecting that when the first LDAP url is down, the second will be user to authenticate the users. Apparently, it's only using the first one and there's no backup for the second one. Meaning, if the first one is down (while the other one works), the users will still not be able to authenticate (although the second LDAP works).

Unfortunately, the documentation is not clear in that subject. Could you please update the docs in case someone might also think that that's an LDAP backup system. 

Thanks in advance.
