### ISSUE TITLE
Actuator endpoints returning 404

### ISSUE THREAD

**Issue by ShawnRG** [openanalytics/shinyproxy#400]
Hi

Using version 2.6.1, I can't seem to access the actuator pages.
I have tried adding the following configuration:
```yml
management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health
```
But that still results in a 404:
<img width="304" alt="image" src="https://user-images.githubusercontent.com/35766067/219066751-e6f9cb2e-e0a7-4945-b250-27a537b8d08b.png">
