### ISSUE TITLE
Authentification issue: You took too long to login, please try again.

### ISSUE THREAD

**Issue by feddelegrand7** [openanalytics/shinyproxy#402]
Hi, 

Thanks again for the release of shiny proxy 3.0.0. I encountered an issue though. Using Shiny proxy 2.6.1, the below YAML works but the app freezes when theres's a new release.  However, with Shiny Proxy 3.0.0 (which should have fixed the issue), I cannot even authenticate (see image). I'm running Redis on a docker container with the correct network and password. Any idea of the source of the issue? 

Thanks in advance

![image](https://user-images.githubusercontent.com/28841210/223086750-4da54427-c036-45cc-8c40-f47237081d98.png)

```
proxy:
  store-mode: Redis
  port: 9095
  logo: xxx
  authentication: ldap
  admin-groups: xxx
  container-wait-time: 600000
  stop-proxies-on-shutdown: false
  recover-running-proxies: true
  recover-running-proxies-from-different-config: true
  ldap:
    url: xxx
    user-search-base:
    user-search-filter: (sAMAccountName={0})
    group-search-base: OU=Groups
    group-search-filter: (member={0})
    manager-dn: CN= xxx
    manager-password: xxx
  docker:
      internal-networking: true
  specs:
  - id: xxx
    display-name: xxx
    container-image: xxx
    container-network: xxx
    access-groups: xxx
server:
  servlet.session.timeout: 0
  
spring:
  session:
    store-type: redis
  redis:
    host: xxx
    password: xxx
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  file:
    shinyproxy.log

```
