### ISSUE TITLE
Is it possible to get admin users based on username instead of group?

### ISSUE THREAD

**Issue by Danoontjes** [openanalytics/shinyproxy#405]
Hi,

I would like to set certain users as admin, but there does not seem to be a admin-users config variable.

I am using LDAP to authenticate my users, but our I don't have control over the groups there, and none of the existing groups will do the trick. Also I have been unable to get any 'Roles' from the AD. In the logs I always get "Roles from search: []"

Can I somehow assign the username as group and use that to specify admins? I tried the config below, but that did not work.

My LDAP config:
```
  ldap:
    url: ldap://10.5.66.20:389/dc=my,dc=domain
    user-search-filter: (sAMAccountName={0})
    user-search-base: OU=Comp
    group-search-base: OU=Comp
    group-search-filter: (sAMAccountName={0})
    manager-dn: biolinux-sa@my.domain
    manager-password: xxxxxxxx
```
With the above, users can login correctly, but no groups are found.
