### ISSUE TITLE
template-groups documentation missing properties

### ISSUE THREAD

**Issue by burgerga** [openanalytics/shinyproxy#416]
Currently template-groups in https://www.shinyproxy.io/documentation/configuration/#general shows 

```
proxy:
  template-groups:
    - id: tools
      display-name: Tools
      maintainer: Tesla
    - id: visualisations
      display-name: Visualisations
      maintainer: Einstein
    - id: documentation
      display-name: Documentation
```
however this won't work. The full example (https://github.com/openanalytics/shinyproxy-config-examples/blob/master/05-template-groups/application.yml) shows

```
proxy:
  template-groups:
    - id: tools
      properties:
        display-name: Tools
        maintainer: Tesla
    - id: visualizations
      properties:
        display-name: Visualizations
        maintainer: Einstein
```
this does work, so my guess is display-name and maintainer need to be nested under `properties`.
