### ISSUE TITLE
How can we integrate two keycloak providers? 

### ISSUE THREAD

**Issue by zhonghua7896321** [openanalytics/shinyproxy#421]
I'm using keycloak as authentication provider, current I plan to add a second keycloak, similiar as ldap, however, it keeps failure. 
How can we use two keycloak providers?  Thanks in advance. 

### Working setting for single keycloak provider
```
proxy:
[...]
  authentication: keycloak
  keycloak:
    realm: yoursso
    auth-server-url: http://yoururl.com:8180/auth
    resource: yourresource
    credentials-secret: your-credentials-secret
```

#### Setting 1 - Mirror official [multiple ldap provider setting](https://www.shinyproxy.io/documentation/configuration/#multiple-ldap-providers) 

```
proxy:
[...]
  authentication: keycloak
  keycloak:
  - realm: yoursso
    auth-server-url: http://yoururl.com:8180/auth
    resource: yourresource
    credentials-secret: your-credentials-secret
  - realm: yoursso2
    auth-server-url: http://yoururl2.com:8180/auth
    resource: yourresource2
    credentials-secret: your-credentials-secret
```

**Error info:** org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'keycloakAuthenticationProcessingFilter' defined in class path resource [eu/openanalytics/containerproxy/auth/impl/KeycloakAuthenticationBackend.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.keycloak.adapters.springsecurity.filter.KeycloakAuthenticationProcessingFilter]: Factory method 'keycloakAuthenticationProcessingFilter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'adapterDeploymentContext' defined in class path resource [eu/openanalytics/containerproxy/auth/impl/KeycloakAuthenticationBackend.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.keycloak.adapters.AdapterDeploymentContext]: Factory method 'adapterDeploymentContext' threw exception; nested exception is java.lang.RuntimeException: **Must set 'realm' in config**

#### Setting 2  - No error generated, but only the first keycloak provider work. 
```
proxy:
[...]
  authentication: keycloak
  keycloak:
    realm: yoursso
    auth-server-url: http://yoururl.com:8180/auth
    resource: yourresource
    credentials-secret: your-credentials-secret
  keycloak2:
    realm: yoursso2
    auth-server-url: http://yoururl2.com:8180/auth
    resource: yourresource2
    credentials-secret: your-credentials-secret
```

#### Setting 3  --- completely wrong settings 
```
proxy:
[...]
  authentication: keycloak,keycloak2 
  keycloak:
    realm: yoursso
    auth-server-url: http://yoururl.com:8180/auth
    resource: yourresource
    credentials-secret: your-credentials-secret
  keycloak2:
    realm: yoursso2
    auth-server-url: http://yoururl2.com:8180/auth
    resource: yourresource2
    credentials-secret: your-credentials-secret
```

**Error info:** Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticationBackend' defined in URL [jar:file:/root/shinyproxy/shinyproxy-3.0.1.jar!/BOOT-INF/lib/containerproxy-1.0.1.jar!/eu/openanalytics/containerproxy/auth/AuthenticationBackendFactory.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: **Unknown authentication type:keycloak,keycloak2**
