### ISSUE TITLE
[Documentation improvement] kubernetes-pod-patches example

### ISSUE THREAD

**Issue by Soluyanov** [openanalytics/shinyproxy#424]
There is an issue in the documentation, where using of kubernetes-pod-patches described.
As an example configuration it is written:
```
  - op: add
    path: /spec/containers/0/env/-
    value:
    - name: SOME_PASSWORD
      valueFrom:
        secretKeyRef:
        name: some-password
        key: password
```
Should be:
```
  - op: add
    path: /spec/containers/0/env/-
    value:
      name: SOME_PASSWORD
      valueFrom:
        secretKeyRef:
          name: some-password
          key: password
```
