### ISSUE TITLE
Run multiple instances of shinyproxy

### ISSUE THREAD

**Issue by samaprashanth** [openanalytics/shinyproxy#452]
Hi,
I am using the .deb version of the Shinyproxy on a linux server and everything is working perfect. In this method, we configure everything by editing the /etc/shinyproxy/application.yml file. 
I want to run 2 different shiny apps on different ports using shinyproxy. I am assuming in order to do that we would need two different application.yml files one for each application but when we use the service version i.e deb package version of shinyproxy we can only use a single location for the config file as mentioned above right?
Is there a way to do that within a single config file or any other way to be able to do this?
Any help is much appreciated.

Thank you..!!!

**Comment by samaprashanth** [comment]
I was also trying to test it using jar file. From the documentation, if we want to use a custom config file we have to move the application.yml file to the same location where our jar file exists and run the command from the same directory. I did the same but for some reason its always trying to connect to Port 9090 even though I changed it in my application.yml file. Below I am attaching the config file and log file.

application.yml file
`
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  # Example: 'simple' authentication configuration
  users:
  - name: jack
    password: password
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians 
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo

logging:
  file:
    name: shinyproxy.log
`

log file:

`
2023-09-13 20:59:36.974  INFO 36221 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2023-09-13 20:59:36.978  INFO 36221 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2023-09-13 20:59:37.013  INFO 36221 --- [main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 24 ms. Found 0 Redis repository interfaces.
2023-09-13 20:59:37.083  INFO 36221 --- [main] faultConfiguringBeanFactoryPostProcessor : No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
2023-09-13 20:59:37.092  INFO 36221 --- [main] faultConfiguringBeanFactoryPostProcessor : No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
2023-09-13 20:59:37.421  INFO 36221 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.integration.config.IntegrationManagementConfiguration' of type [org.springframework.integration.config.IntegrationManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-09-13 20:59:37.428  INFO 36221 --- [main] trationDelegate$BeanPostProcessorChecker : Bean 'integrationChannelResolver' of type [org.springframework.integration.support.channel.BeanFactoryChannelResolver] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2023-09-13 20:59:37.698  WARN 36221 --- [main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2023-09-13 20:59:37.721  INFO 36221 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-09-13 20:59:37.722  INFO 36221 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1621 ms
2023-09-13 20:59:37.761  INFO 36221 --- [main] e.o.c.service.IdentifierService          : ShinyProxy runtimeId:                   4754eb3f-b8a0-42fb-9d7b-16811b43f45d
2023-09-13 20:59:37.813  INFO 36221 --- [main] e.o.c.service.IdentifierService          : ShinyProxy instanceID (hash of config): 73f9d390ca5c0d63bd2a6b841449e2f98c4cee48
2023-09-13 20:59:38.300  INFO 36221 --- [main] o.s.boot.web.servlet.RegistrationBean    : Filter orderedFormContentFilter was not registered (disabled)
2023-09-13 20:59:38.592  INFO 36221 --- [main] o.s.s.web.DefaultSecurityFilterChain     : Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@2dbd803f, org.springframework.security.web.session.ForceEagerSessionCreationFilter@3e48e859, org.springframework.security.web.session.ForceEagerSessionCreationFilter@56ba8773, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@31ddd4a4, org.springframework.security.web.context.SecurityContextPersistenceFilter@6ceb7b5e, org.springframework.security.web.header.HeaderWriterFilter@6f8e0cee, org.springframework.security.web.csrf.CsrfFilter@b9dfc5a, org.springframework.security.web.authentication.logout.LogoutFilter@4c98a6d5, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@55b8dbda, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@1a5f7e7c, eu.openanalytics.containerproxy.util.AppRecoveryFilter@36a7abe1, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@f14e5bf, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@4784013e, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@5b22b970, org.springframework.security.web.session.SessionManagementFilter@5116ac09, org.springframework.security.web.access.ExceptionTranslationFilter@426e505c, eu.openanalytics.shinyproxy.AuthenticationRequiredFilter@22d1886d, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@773c0293]
2023-09-13 20:59:38.606  WARN 36221 --- [main] org.thymeleaf.templatemode.TemplateMode  : [THYMELEAF][main] Template Mode 'HTML5' is deprecated. Using Template Mode 'HTML' instead.
2023-09-13 20:59:38.864  INFO 36221 --- [main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2023-09-13 20:59:39.823  INFO 36221 --- [main] o.s.l.c.support.AbstractContextSource    : Property 'userDn' not set - anonymous context will be used for read-write operations
2023-09-13 20:59:40.020  INFO 36221 --- [main] o.s.i.endpoint.EventDrivenConsumer       : Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-09-13 20:59:40.020  INFO 36221 --- [main] o.s.i.channel.PublishSubscribeChannel    : Channel 'ShinyProxy.errorChannel' has 1 subscriber(s).
2023-09-13 20:59:40.021  INFO 36221 --- [main] o.s.i.endpoint.EventDrivenConsumer       : started bean '_org.springframework.integration.errorLogger'
2023-09-13 20:59:40.028  INFO 36221 --- [main] io.undertow                              : starting server: Undertow - 2.2.21.Final
2023-09-13 20:59:40.048  INFO 36221 --- [main] org.xnio                                 : XNIO version 3.8.8.Final
2023-09-13 20:59:40.057  INFO 36221 --- [main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.8.Final
2023-09-13 20:59:40.119  INFO 36221 --- [main] org.jboss.threads                        : JBoss Threads version 3.1.0.Final
2023-09-13 20:59:40.196  INFO 36221 --- [main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 8080 (http)
2023-09-13 20:59:40.271  INFO 36221 --- [main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2023-09-13 20:59:40.272  INFO 36221 --- [main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 69 ms
2023-09-13 20:59:40.280  INFO 36221 --- [main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 2 endpoint(s) beneath base path '/actuator'
2023-09-13 20:59:40.552  INFO 36221 --- [main] io.undertow                              : starting server: Undertow - 2.2.21.Final
2023-09-13 20:59:40.589  INFO 36221 --- [main] io.undertow                              : stopping server: Undertow - 2.2.21.Final
2023-09-13 20:59:40.590  WARN 36221 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 9090 is already in use
2023-09-13 20:59:40.592  WARN 36221 --- [main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 9090 is already in use
2023-09-13 20:59:40.592  INFO 36221 --- [main] o.s.i.endpoint.EventDrivenConsumer       : Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2023-09-13 20:59:40.593  INFO 36221 --- [main] o.s.i.channel.PublishSubscribeChannel    : Channel 'ShinyProxy.errorChannel' has 0 subscriber(s).
2023-09-13 20:59:40.593  INFO 36221 --- [main] o.s.i.endpoint.EventDrivenConsumer       : stopped bean '_org.springframework.integration.errorLogger'
2023-09-13 20:59:40.608  INFO 36221 --- [main] io.undertow                              : stopping server: Undertow - 2.2.21.Final
2023-09-13 20:59:40.620  INFO 36221 --- [main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-09-13 20:59:40.635 ERROR 36221 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 9090 was already in use.

Action:

Identify and stop the process that's listening on port 9090 or configure this application to listen on another port.


`

**Comment by essemenov** [comment]
Hi @samaprashanth ,

Shinyproxy is Springboot framework application. It means you can
create single application.yaml config and run multiple instances of shinyproxy and point them to single application.yaml file.
See an example below 
```
---
# This file is managed by Ansible
server:
  forward-headers-strategy: native
  useForwardHeaders: true
proxy:
  title: "Test"
  # logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  bind-address: "127.0.0.1"
  port: "8082"
  # Docker configuration
  container-backend: docker
  docker:
    cert-path: /home/none
    url: "http://127.0.0.1:2375"
  authentication: simple
  admin-groups: shinyproxyadmin

  specs:
    - id: 01_hello
        display-name: Hello Application
        description: Application which demonstrates the basics of a Shiny app
        container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
        container-image: openanalytics/shinyproxy-demo

logging:
  file:
    name: "/opt/shinyproxy/shinyproxy.log"
  level:
    root: DEBUG
---
spring:
  profiles: prod
management:
  server:
    port: 9091
proxy:
  port: "8091"
  docker:
    port-range-start: 20000
  users:
    - name: prod
      password: prod
      groups: shinyproxyadmin
    - name: produser
      password: devuser
      groups: ['USER']
---
spring:
  profiles: dev
management:
  server:
    port: 9092
proxy:
  port: "8092"
  docker:
    port-range-start: 30000
  users:
    - name: dev
      password: dev
      groups: [shinyproxyadmin]
    - name: devuser
      password: devuser
      groups: ['USER']
```

This file contains default Springboot profile, prod and dev. The last tow are our custom profiles.
Dev and prod profiles are overrided settings in default profile if you add an extra parameter to command line

To use DEV-profile, please, run
```
/usr/bin/java -jar -Dspring.profiles.active=dev /opt/shinyproxy/shinyproxy-3.0.2.jar
```
shinyproxy is available on 8092 port, managment port is 9092. Containers ports are started from 30000.

To use PROD-profile, please, run 
```
/usr/bin/java -jar -Dspring.profiles.active=prod /opt/shinyproxy/shinyproxy-3.0.2.jar
```
shinyproxy is available on 8091 port, managment port is 9091. Containers ports are started from 20000.


To run both command as systemd-service you need to create two service definition.
Example https://github.com/openanalytics/shinyproxy/blob/develop/src/deb/shinyproxy.service

---
Evgenii
