### ISSUE TITLE
Unique email for Report Issue button per Application

### ISSUE THREAD

**Issue by corey-dawson** [openanalytics/shinyproxy#467]
Different apps are created by multiple users. The Report Issue configuration currently only allows users to send feedback to a single email. It would be more ideal to define a feedback email per app. When that app is launched, it will use the app specified email configuration . If there is no app configuration, email falls back to the global setting

Current feedback config

```yaml
proxy:
  support:
    mail-to-address: some.user@somedomain.com
```
