### ISSUE TITLE
proxy.kubernetes.node-selector not working

### ISSUE THREAD

**Issue by cdenneen** [openanalytics/shinyproxy#471]
Based on the documentation it appear the following is the proper syntax:

```
  proxy:
    stop-proxies-on-shutdown: false
    landing-page: /
    favicon-path: favicon.ico
    heartbeat-rate: 10000
    heartbeat-timeout: 60000
    containerBackend: kubernetes
    kubernetes:
      internal-networking: true
      image-pull-policy: Always
      node-selector: "kubernetes.io/arch=amd64"
```

However I have seen the following in some people's examples:

```
proxy:
  kubernetes:
    node-selector:
      kubernetes.io/arch: amd64
```

honestly the later would be preferred but right now the proxy comes up without the nodeSelctor actually set:

```
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

But you can see from inspecting the `shinyproxy` resource it is there:

```
$ kubectl -n shinyproxy get shinyproxy proxy1 -o jsonpath='{.spec.proxy.kubernetes.node-selector}'
kubernetes.io/arch=amd64
```

I'm using shinyproxy-operator: 2.0.0

**Comment by LEDfan** [comment]
Hi

The first syntax you posted is the correct one, e.g.:

```yaml
proxy:
   kubernetes:
      node-selector: "kubernetes.io/os=linux,kubernetes.io/arch=amd64"
```

I will add this example to the documentation.

Please note that this selector is added to the pods created by ShinyProxy, such as a Shiny app you specified in the ShinyProxy config. This configuration is not used by the operator and therefore is not added to the ShinyProxy pod itself. If you need to add a nodeSelector to the shinyproxy pod itself, you can use `kubernetesPodTemplateSpecPatches`, see: https://github.com/openanalytics/shinyproxy-operator/tree/master/docs/deployment#modify-the-shinyproxy-pod
