### ISSUE TITLE
Cannot configure OpenID (Okta) as authentication method

### ISSUE THREAD

**Issue by ggarza31416** [openanalytics/shinyproxy#524]
I have been struggling trying to configure my Okta app as authentication method for my ShinyProxy installation. 
These are my configuration values:

```
  proxy:
    admin-groups: scientists
    authentication: openid
    openid:
      auth-url: https://my-okta-domain.com/oauth2/v1/authorize
      token-url: https://my-okta-domain.com/oauth2/v1/token
      jwks-url: https://my-okta-domain.com/oauth2/v1/keys
      client-id: <redacted>
      client-secret: <redacted>
```
In my Okta app I have just configured just the next value: 
Sign-in redirect URIs: `https://my-shinyproxy.domain`

Does anyone know what is missing here? 

Also, I have checked the logs from ShinyProxy but it is not showing any error.
