### ISSUE TITLE
Fail in reverse proxy with nginx

### ISSUE THREAD

**Issue by Aiuthss** [openanalytics/shinyproxy#534]
Hi, thanks for the great package.
I am looking to implement authentication using Google's OpenID provider. I also intend to enable SSL connections via Nginx reverse proxy.
I have configured Shinyproxy and Nginx as follows and set https://mydomain/login/oauth2/code/shinyproxy as the approved redirect URI in the console.
I then accessed https://mydomain with the following results
```
Error 400: redirect_uri_mismatch
Request details 
redirect_uri=http://mydomain/login/oauth2/code/shinyproxy 
flowName=GeneralOAuthFlow
```
Why is the redirect_uri HTTP not HTTPS?
Here is my Shinyproxy and Nginx configuration.

Shinyproxy setting
```
proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: openid
  admin-groups: scientists
  container-wait-time: 999000
  container-log-path: ./container-logs
  openid:
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    token-url: https://www.googleapis.com/oauth2/v4/token
    jwks-url: https://www.googleapis.com/oauth2/v3/certs
    client-id: xxx.apps.googleusercontent.com
    client-secret: yyy
    username-attribute: email

  specs:
    - id: euler
      display-name: Euler
      description: Application to calculate euler's e
      container-image: openanalytics/shinyproxy-shiny-demo-minimal
logging:
  file:
    name: shinyproxy.log
```

Nginx setting
```
server {
        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;
        server_name mydomain; # managed by Certbot
        access_log /var/log/nginx/shinyproxy.access.log;
        error_log /var/log/nginx/shinyproxy.error.log error;

        location / {
                proxy_pass http://127.0.0.1:8080/;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 600s;

                proxy_redirect    off;
                proxy_set_header  Host              $http_host;
                proxy_set_header  X-Real-IP         $remote_addr;
                proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Proto $scheme;
        }
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = mydomain) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
        listen 80 ;
        listen [::]:80 ;
    server_name mydomain;
    return 404; # managed by Certbot
}
```

supplement
If I specify http://mydomain:8080/login/oauth2/code/shinyproxy as the approved redirect URI and connect to http://mydomain:8080, I get the expected results.
