### ISSUE TITLE
admin page access when all apps are public (`authentication: none`)

### ISSUE THREAD

**Issue by MalditoBarbudo** [openanalytics/shinyproxy#552]
Is there a way to have an authenticated user to access the admin page while maintaining all apps public? 

For example:
```
proxy:
  users:
    - name: gandalf
      password: youshallnotpass
      groups: magicians
  admin-groups: magicians
  authentication: none
```

Would this configuration allow `gandalf` user to access the admin page while allowing unauthenticated users to access the apps?

I'm aware of #330 and the impossibility of having both apps, autheticated and public, in the same shinyproxy instance. But this is not quite the same as all apps are public in this case, but access to the admin page is needed for the shinyproxy server admin.
