### ISSUE TITLE
Replace X-Frame-Options: allow-from with Content-Security-Policy: frame-ancestors for iframe embedding support

### ISSUE THREAD

**Issue by kialuna** [openanalytics/shinyproxy#561]
Hi,

We're using ShinyProxy to serve an app at https://webapps.kwtg.uk/, which is embedded via an iframe in a parent site at https://www.kentwildlifetrust.org.uk/.

According to the documentation, the recommended method to allow iframe embedding is:

```
server:
  frame-options: allow-from https://www.kentwildlifetrust.org.uk
```
However for some users on Chrome, this results in the following error in the console: 

`kent-local-wildlife-sites:1 Invalid 'X-Frame-Options' header encountered when loading 'https://webapps.kwtg.uk/': 'allow-from https://www.kentwildlifetrust.org.uk' is not a recognized directive. The header will be ignored.`

From what I can tell, this is because X-Frame-Options: ALLOW-FROM is [obsolete in most modern browsers.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/X-Frame-Options#:~:text=ALLOW%2DFROM%20origin,should%20use%20instead.)

It seems that modern browsers rely on the Content-Security-Policy: frame-ancestors directive instead.

e.g. `Content-Security-Policy: frame-ancestors https://www.kentwildlifetrust.org.uk;`

I’d like to request:

- Support for configuring `Content-Security-Policy: frame-ancestors` via `application.yml`
- Deprecation (or at least a warning) about `X-Frame-Options: allow-from` being ineffective
- Updated documentation to reflect the use of `frame-ancestors` for iframe support

Thanks very much for your work in upkeeping this project. 

Best,
Kia

**Comment by LEDfan** [comment]
Hi,

You can add the Content-Security Policy as follows:

```yaml
proxy:
  api-security:
    custom-headers:
    - name: Content-Security-Policy
      value: 'frame-ancestors https://www.kentwildlifetrust.org.uk;'
```

See https://shinyproxy.io/documentation/configuration/#custom-headers
Please let us know whether this solves your issue, we will then update the documentation.

**Comment by kialuna** [comment]
I changed it to also allow 'self' and that solved the issue :)

```
proxy:
  api-security:
    custom-headers:
    - name: Content-Security-Policy
      value: "frame-ancestors 'self' https://www.kentwildlifetrust.org.uk;"
```
