### ISSUE TITLE
Force OIDC auth redirect_uri to be https

### ISSUE THREAD

**Issue by tknoch8** [openanalytics/shinyproxy#564]
I've been experimenting with shinyproxy operator and it's been quite useful. When experimenting with oidc for auth, I am having issues with the redirect_uri. Our reverse proxy sets both `X-Forwarded-For` and `X-Forwarded-Proto` but that is getting lost in the kubernetes load balancer which only sees http. Because of this the redirect_uri has an http scheme when it needs https. I have tried setting the following ingress patch but it still retains the http redirect_uri.
```
kubernetesIngressPatches: |
    - op: add
      path: /metadata/annotations
      value:
        # http://nginx.ingress.kubernetes.io/proxy-buffer-size
        nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
        # http://nginx.ingress.kubernetes.io/proxy-body-size
        nginx.ingress.kubernetes.io/proxy-body-size: "300m"
        # http://nginx.ingress.kubernetes.io/use-forwarded-headers
        nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
        # http://nginx.ingress.kubernetes.io/use-proxy-protocol
        nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    - op: add
      path: /spec/ingressClassName
      value: nginx
    - op: replace # This assumes the ShinyProxy operator generates a path at this JSON path
      path: /spec/rules/0/http/paths/0/path
      value: /apps
    - op: add # This assumes pathType is not set by default or you want to ensure it's Prefix
      path: /spec/rules/0/http/paths/0/pathType
      value: Prefix
```
If there is something I am missing in the patches, I would love to fix it. But if not, it would be great if there were a proxy or server setting where we could force the redirect_uri to be https.
