### ISSUE TITLE
503 Response being returned from Shinyproxy to Loadbalancer

### ISSUE THREAD

**Issue by mcrmonkey** [openanalytics/shinyproxy#65]
I have a shinyproxy sat behind a google load balancer and when accessing one of the configured applications the proxy will return a 503 response when some assets provided by the application are accessed.

The assets that fail aren't always the same though. Sometimes the logo on the applications start page doesn't load then it will when the page is reloaded and the browser cache ignored. The same can be said for CSS documents too.

The Loadbalancer is provided via the Google compute service and is configured to handle the SSL stuff for the proxy. Everything behind the loadbalancer for the moment is just HTTP

My shinyproxy config is:

```yaml

shiny:
  proxy:
    title: Test-shiny
    logo-url: https://assets.local/logo.png
    landing-page: /
    heartbeat-rate: 1000
    heartbeat-timeout: 1000000
    container-wait-time: 1200000
    hide-navbar: true
    port: 8080
    authentication: none
    docker:
      url: http://localhost:2375
      port-range-start: 20000
  apps:
  - name: test-app
    display-name: test-application
    description: test application
    docker-image: test-r-app:latest

logging:
  file:
    shinyproxy.log
  level:
    root: DEBUG

```

I have packet captures from inside the docker network that show all is well and the request is served properly.
The packet captures i have from shinyproxy however show its returning a 503 to the loadbalancer IP's

Network diagram of sorts:

{World} --> [Google LB] --> [shiny proxy instance  (Docker service) ]

If the LB is turned off shiny seems to be fine, however i kind of need it for what i want to do

Does there need to be extra config set for shiny to make it play nice with a loadbalancer ?
