### ISSUE TITLE
Authenticating against Active Directory without bind authentication support

### ISSUE THREAD

**Issue by holtgrewe** [openanalytics/shinyproxy#7]
I want to setup shinyproxy against an Active Directory server that does not support bind authentication support as the directory is highly structured and users are stored below many different paths.

What worked well for me so far and what I could configure with Spring XML based configuration was to use the password comparison authentication module.

When setting up shinyproxy as in the manual, shinyproxy never tries to bind with the `manager-dn` and `manager-password` but goes straight to the logged in user.

The relevant snippet in my configuration looks as follows.

```
    # LDAP configuration
    ldap:
      url: ldap://s-dc-bih01.example.com/
      user-dn-pattern: sAMAccountName={0}
      user-search-base: OU=sub1,DC=example,DC=com
      group-search-base:
      group-search-filter: (uniqueMember={0})
      manager-dn: CN=user,OU=sub2,OU=sub1,DC=example,DC=com
      manager-password: XXXREDACTEDXXX

security:
  basic:
    enabled: false
```

Am I doing anything wrong?

Thanks
