### ISSUE TITLE
Possibility to set context path 

### ISSUE THREAD

**Issue by Ununnilium** [openanalytics/shinyproxy#8]
To run multiple web services behind Nginx or Apache with a single domain name, it's useful to be able setting a context path, e.g. https://example.com/shinyproxy instead of https://example.com. I have made therefore the necessary changes to the code: https://github.com/openanalytics/shinyproxy/compare/master...Ununnilium:master. With this changes, the context path can then be defined in `application.yml`:
```yml
shiny:
  ...
spring:
  ...
logging:
  ...
server:
  contextPath: "/shinyproxy"
```
I have never used Spring Boot before, therefore I'm not sure if the code quality of my changes are good enough. If there are good enough, can you add them? If not, would it be possible that this functionality is added in future?
