### ISSUE TITLE
App configuration in individual files

### ISSUE THREAD

**Issue by innir** [openanalytics/shinyproxy#91]
Hi,

if would be really useful if one could store the configuration for the apps in individual files, like:

- application.yml
- application.yml.d/
  - app1.yml
  - app2.yml

Content of `app*.yml` would be

```
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: [scientists, mathematicians]
```

This would make deploying new apps much easier as one could just copy a new file into the directory instead of editing application.yml.
